-- Mondo Medical -- Supabase schema + data migration.
-- Run this ONCE in the Supabase SQL Editor (Project -> SQL Editor -> New query -> Run).

create extension if not exists pgcrypto;

-- Public bucket for product photos, uploaded by hand from the Supabase
-- dashboard (Storage -> product-photos). Name files "<product-id>.jpg" or
-- "<product-id>--<brand-id>.jpg" for a brand-specific photo. Public bucket
-- objects are served without needing extra storage RLS policies.
insert into storage.buckets (id, name, public)
values ('product-photos', 'product-photos', true)
on conflict (id) do update set public = true;

create table if not exists brands (
  id text primary key,
  name text not null
);

create table if not exists products (
  id text primary key,
  type text not null check (type in ('equipment','instrument')),
  category text not null,
  name_fr text not null,
  name_en text not null,
  model text not null default '',
  brand_ids text[] not null default '{}',
  created_at timestamptz not null default now()
);

create table if not exists quote_counters (
  year int primary key,
  count int not null default 0
);

create or replace function next_quote_reference() returns text
language plpgsql security definer as $$
declare
  y int := extract(year from now())::int;
  n int;
begin
  insert into quote_counters(year, count) values (y, 1)
  on conflict (year) do update set count = quote_counters.count + 1
  returning count into n;
  return 'QT-' || y || '-' || lpad(n::text, 4, '0');
end;
$$;

create table if not exists quote_requests (
  id uuid primary key default gen_random_uuid(),
  reference text not null unique default next_quote_reference(),
  created_at timestamptz not null default now(),
  status text not null default 'new',
  customer_type text,
  first_name text,
  last_name text,
  company text,
  email text,
  phone text,
  country text,
  city text,
  address text,
  contact_method text,
  message text,
  items jsonb not null default '[]'
);

alter table brands enable row level security;
alter table products enable row level security;
alter table quote_counters enable row level security;
alter table quote_requests enable row level security;

drop policy if exists "Public read brands" on brands;
create policy "Public read brands" on brands for select using (true);

drop policy if exists "Public read products" on products;
create policy "Public read products" on products for select using (true);

drop policy if exists "Public insert quote_requests" on quote_requests;
create policy "Public insert quote_requests" on quote_requests for insert with check (true);

-- quote_counters: no public policies at all -- only next_quote_reference()
-- (SECURITY DEFINER) may touch it. quote_requests: no public select/update/
-- delete policy either -- visitors can submit a request but never read,
-- edit or delete requests (yours or anyone else's). View/manage requests
-- from the Supabase Table Editor (uses your own account, not the public key).

-- ---- Data ----

insert into brands (id, name) values
  ('3m-bair-hugger', '3M BAIR HUGGER'),
  ('a2-medical', 'A2 MEDICAL'),
  ('acem', 'ACEM'),
  ('ackerma', 'ACKERMA'),
  ('aeonmed', 'AEONMED'),
  ('aesculap', 'AESCULAP'),
  ('air-liquide-medical-systems', 'AIR LIQUIDE MEDICAL SYSTEMS'),
  ('airon', 'AIRON'),
  ('allengers', 'ALLENGERS'),
  ('amel', 'AMEL'),
  ('angell', 'ANGELL'),
  ('aouha', 'AOUHA'),
  ('at-os', 'AT-OS'),
  ('aurion', 'AURION'),
  ('axent', 'AXENT'),
  ('aygun', 'AYGUN'),
  ('b105', 'B105'),
  ('b125', 'B125'),
  ('bair-hugger', 'BAIR HUGGER'),
  ('bemems', 'BEMEMS'),
  ('biocare', 'BIOCARE'),
  ('biomed', 'BIOMED'),
  ('blt', 'BLT'),
  ('bmc-medical', 'BMC MEDICAL'),
  ('bmk', 'BMK'),
  ('bowa', 'BOWA'),
  ('brainlab', 'BRAINLAB'),
  ('brawn', 'BRAWN'),
  ('capnomed', 'CAPNOMED'),
  ('cefar-compex', 'CEFAR COMPEX'),
  ('celitron', 'CELITRON'),
  ('chine', 'CHINE'),
  ('choyang', 'CHOYANG'),
  ('comen', 'COMEN'),
  ('conmed', 'CONMED'),
  ('covidien', 'COVIDIEN'),
  ('creative', 'CREATIVE'),
  ('danmedics', 'DANMEDICS'),
  ('depuy-synthes', 'DEPUY SYNTHES'),
  ('depy', 'DEPY'),
  ('dessilons', 'DESSILONS'),
  ('dgm', 'DGM'),
  ('divers', 'DIVERS'),
  ('dms', 'DMS'),
  ('dms-stratos', 'DMS STRATOS'),
  ('drager', 'DRAGER'),
  ('ds-mareef', 'DS MAREEF'),
  ('eberle', 'EBERLE'),
  ('edan', 'EDAN'),
  ('elips', 'ELIPS'),
  ('ems', 'EMS'),
  ('endolook', 'ENDOLOOK'),
  ('enmind', 'ENMIND'),
  ('erbe', 'ERBE'),
  ('f-p', 'F&P'),
  ('falco-evo', 'FALCO EVO'),
  ('famed', 'FAMED'),
  ('fazzini', 'FAZZINI'),
  ('firstmed', 'FIRSTMED'),
  ('fresenius', 'FRESENIUS'),
  ('fujifilm', 'FUJIFILM'),
  ('ge', 'GE'),
  ('genoray', 'GENORAY'),
  ('getemed', 'GETEMED'),
  ('giotto', 'GIOTTO'),
  ('gmm', 'GMM'),
  ('hanlim', 'HANLIM'),
  ('hawkmed', 'HAWKMED'),
  ('herman', 'HERMAN'),
  ('hermann', 'HERMANN'),
  ('hersill', 'HERSILL'),
  ('heyer', 'HEYER'),
  ('hillrom', 'HILLROM'),
  ('hitachi', 'HITACHI'),
  ('hologic', 'HOLOGIC'),
  ('holtex', 'HOLTEX'),
  ('huidamed', 'HUIDAMED'),
  ('ilo', 'ILO'),
  ('innomed', 'INNOMED'),
  ('inomed', 'INOMED'),
  ('integra', 'INTEGRA'),
  ('italray', 'ITALRAY'),
  ('kawe', 'KAWE'),
  ('konsung', 'KONSUNG'),
  ('lawton', 'LAWTON'),
  ('libherr', 'LIBHERR'),
  ('lifotronic', 'LIFOTRONIC'),
  ('linea-life', 'LINEA LIFE'),
  ('linet', 'LINET'),
  ('lowentein', 'LOWENTEIN'),
  ('magnamed', 'MAGNAMED'),
  ('maquet', 'MAQUET'),
  ('mcm', 'MCM'),
  ('medcaptain', 'MEDCAPTAIN'),
  ('medifa', 'MEDIFA'),
  ('medikal', 'MEDIKAL'),
  ('medtronic', 'MEDTRONIC'),
  ('mespa', 'MESPA'),
  ('metaltronic', 'METALTRONIC'),
  ('microaire', 'MICROAIRE'),
  ('mindray', 'MINDRAY'),
  ('nihon-koden', 'NIHON KODEN'),
  ('nitrocare', 'NITROCARE'),
  ('nopa', 'NOPA'),
  ('novag', 'NOVAG'),
  ('olympus', 'OLYMPUS'),
  ('optium', 'OPTIUM'),
  ('osiris', 'OSIRIS'),
  ('osteosys', 'OSTEOSYS'),
  ('perlove', 'PERLOVE'),
  ('philips', 'PHILIPS'),
  ('precisa', 'PRECISA'),
  ('precision', 'PRECISION'),
  ('primedic', 'PRIMEDIC'),
  ('reda', 'REDA'),
  ('resmed', 'RESMED'),
  ('riester', 'RIESTER'),
  ('ruidi', 'RUIDI'),
  ('rz-medizin', 'RZ-MEDIZIN'),
  ('samsung', 'SAMSUNG'),
  ('schiller', 'SCHILLER'),
  ('schroder', 'SCHRODER'),
  ('senocrystalnova', 'SENOCRYSTALNOVA'),
  ('siar', 'SIAR'),
  ('siare', 'SIARE'),
  ('siemens', 'SIEMENS'),
  ('sinomdt', 'SINOMDT'),
  ('sirusmed', 'SIRUSMED'),
  ('smam', 'SMAM'),
  ('smith', 'SMITH'),
  ('smith-nephew', 'SMITH & NEPHEW'),
  ('sonoscape', 'SONOSCAPE'),
  ('soring', 'SORING'),
  ('stephanix', 'STEPHANIX'),
  ('surgicon', 'SURGICON'),
  ('teleflex', 'TELEFLEX'),
  ('tni', 'TNI'),
  ('tontarra', 'TONTARRA'),
  ('traveller', 'TRAVELLER'),
  ('tts', 'TTS'),
  ('villa', 'VILLA'),
  ('visco', 'VISCO'),
  ('weinmann', 'WEINMANN'),
  ('wolf', 'WOLF'),
  ('yong-won', 'YONG WON'),
  ('ziehm-imagin', 'ZIEHM IMAGIN'),
  ('zimmerbiomet', 'ZIMMERBIOMET')
on conflict (id) do update set name = excluded.name;

insert into products (id, type, category, name_fr, name_en, model, brand_ids) values
  ('adaptateur-pour-uretrotomie-1', 'instrument', 'autre', 'Adaptateur Pour Uretrotomie', 'Urethrotomy Adapter', '', ARRAY['lawton','reda']::text[]),
  ('aiguille-de-palmere-3', 'instrument', 'aiguilles-canules', 'Aiguille De Palmere', 'Palmer Needle', '', ARRAY['aesculap','lawton','tontarra','wolf']::text[]),
  ('aiguille-de-ponction-long-4', 'instrument', 'aiguilles-canules', 'Aiguille De Ponction Long', 'Long Puncture Needle', '', ARRAY['aesculap','lawton','mcm','reda','tontarra']::text[]),
  ('aiguille-first-pass-pack-de-5-unite-5', 'instrument', 'aiguilles-canules', 'Aiguille First Pass Pack De 5 Unite', 'First Pass Needle, Pack of 5', '', ARRAY['lawton','reda','smith-nephew']::text[]),
  ('aiguille-palmere-6', 'instrument', 'aiguilles-canules', 'Aiguille Palmere', 'Palmer Needle', '', ARRAY['aesculap','lawton','mcm','reda','tontarra']::text[]),
  ('aiguilles-de-ponction-diam-05mm-7', 'instrument', 'aiguilles-canules', 'Aiguilles De Ponction Diam 05mm', 'Puncture Needles, 05mm Diameter', '', ARRAY['aesculap','hermann','lawton','mcm','olympus','reda','rz-medizin','tontarra']::text[]),
  ('aiguilles-de-verre-d-2-1mm-c12-l-15cm-8', 'instrument', 'aiguilles-canules', 'Aiguilles De Verre D 2.1mm C12 L 15cm', 'Glass Needles, D 2.1mm, C12, L 15cm', '', ARRAY['aesculap','hermann','lawton','mcm','olympus','reda','rz-medizin','tontarra','wolf']::text[]),
  ('aiguilles-de-verre-d-2-1mm-l-12cm-9', 'instrument', 'aiguilles-canules', 'Aiguilles De Verre D 2.1mm L 12cm', 'Glass Needles, D 2.1mm, L 12cm', '', ARRAY['aesculap','hermann','lawton','mcm','olympus','reda','rz-medizin','tontarra','wolf']::text[]),
  ('amplificateur-cutane-10', 'equipment', 'autre', 'Amplificateur Cutane', 'Cutaneous Amplifier', '', ARRAY['zimmerbiomet']::text[]),
  ('appareil-de-radio-numerise-appareil-rxi-11', 'equipment', 'imagerie', 'Appareil De Radio Numerise Appareil Rxi', 'Digital X-Ray Unit, Rxi Unit', '', ARRAY['philips','precision','stephanix','villa']::text[]),
  ('appareil-de-radio-numerise-l-appareil-rxi-12', 'equipment', 'imagerie', 'Appareil De Radio (Numérise) L''Appareil Rxi', 'Digital X-Ray Unit, the Rxi Unit', 'APELEM OPTIMA', ARRAY['angell','dms']::text[]),
  ('appareil-de-radio-standard-mobile-pour-les-sur-place-13', 'equipment', 'imagerie', 'Appareil De Radio Standard Mobile (Pour Les Sur Place )', 'Standard Mobile X-Ray Unit (for On-Site Use)', 'PLX101A', ARRAY['allengers','gmm','italray','perlove','siemens','smam','stephanix','traveller','villa']::text[]),
  ('appareille-de-radio-frequence-pour-reeducation-winback-ou-medtronic-kinesitherapie-14', 'equipment', 'imagerie', 'Appareille De Radio Fréquence Pour Réeducation /Winback Ou Medtronic (Kinésithérapie)', 'Radiofrequency Device for Rehabilitation / Winback or Medtronic (Physiotherapy)', '', ARRAY['medtronic']::text[]),
  ('arbre-flexible-tete-alesage-non-fixe-15', 'instrument', 'autre', 'Arbre Flexible Tete Alesage Non Fixe', 'Flexible Shaft, Non-Fixed Reamer Head', '', ARRAY['mcm']::text[]),
  ('arceau-mobile-scopie-16', 'equipment', 'imagerie', 'Arceau Mobile (Scopie)', 'Mobile C-Arm (Fluoroscopy)', 'OEC ONE', ARRAY['ge','genoray','gmm','perlove','philips','siemens','ziehm-imagin']::text[]),
  ('armoire-de-stockage-pour-08-endoscopes-17', 'equipment', 'bloc-operatoire', 'Armoire De Stockage Pour 08 Endoscopes', 'Storage Cabinet for 08 Endoscopes', '', ARRAY['at-os','choyang','hanlim','visco']::text[]),
  ('arthropompe-18', 'equipment', 'bloc-operatoire', 'Arthropompe', 'Arthroscopy Pump', '', ARRAY['conmed','eberle','smith-nephew','wolf','zimmerbiomet']::text[]),
  ('aspirateur-chirurgical-19', 'equipment', 'autre', 'Aspirateur Chirurgical', 'Surgical Suction Unit', '', ARRAY['hersill']::text[]),
  ('assistants-d-instrumentation-pour-table-d-operation-20', 'equipment', 'bloc-operatoire', 'Assistants D''Instrumentation Pour Table D''Opération', 'Instrument Assist Attachments for Operating Table', '', ARRAY['amel']::text[]),
  ('autoclave-21', 'equipment', 'bloc-operatoire', 'Autoclave', 'Autoclave', '', ARRAY['celitron','dgm']::text[]),
  ('autostatiques-11cm-3-x3-griffes-22', 'instrument', 'autre', 'Autostatiques 11cm 3 x3 Griffes', 'Self-Retaining Retractor, 11cm, 3x3 Teeth', '', ARRAY['aesculap','holtex','lawton','mcm','nopa','precisa','reda']::text[]),
  ('autostatiques-dos-dane-13cm-4-x-4-griffes-23', 'instrument', 'autre', 'Autostatiques Dos Dane 13cm 4 X 4 Griffes', 'Self-Retaining Retractor, Hump Back, 13cm, 4x4 Teeth', '', ARRAY['aesculap','lawton','mcm','nopa','precisa','reda']::text[]),
  ('batterie-autoclavable-microaire-25', 'instrument', 'autre', 'Batterie Autoclavable Microaire', 'Autoclavable Battery, Microaire', '', ARRAY['microaire','reda']::text[]),
  ('bengolea-30cm-avec-griffe-26', 'instrument', 'autre', 'Bengolea 30cm Avec Griffe', 'Bengolea Forceps, 30cm, with Teeth', '', ARRAY['holtex','integra','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('bengolea-30cm-sans-griffe-27', 'instrument', 'autre', 'Bengolea 30cm Sans Griffe', 'Bengolea Forceps, 30cm, without Teeth', '', ARRAY['aesculap','holtex','integra','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('bipolaire-pour-coelioscopie-28', 'instrument', 'optiques-endoscopie', 'Bipolaire Pour Coelioscopie', 'Bipolar Forceps for Laparoscopy', '', ARRAY['bowa','erbe','lawton','mcm','reda']::text[]),
  ('bocal-aspiration-pour-lipo-autoclavable-2-5l-29', 'instrument', 'autre', 'Bocal Aspiration Pour Lipo Autoclavable 2.5L', 'Suction Canister for Liposuction, Autoclavable, 2.5L', '', ARRAY['mcm','reda']::text[]),
  ('bocal-d-aspiration-pour-lipo-autoclavable-2-5l-30', 'instrument', 'autre', 'Bocal D''Aspiration Pour Lipo Autoclavable 2.5L', 'Suction Canister for Liposuction, Autoclavable, 2.5L', '', ARRAY['aesculap']::text[]),
  ('boite-ceolioscopie-complete-31', 'instrument', 'autre', 'Boite Ceolioscopie Complete', 'Complete Laparoscopy Instrument Set', '', ARRAY['lawton','mcm','smith','wolf']::text[]),
  ('boite-d-alesage-et-guides-32', 'instrument', 'autre', 'Boite D''Alésage Et Guides', 'Reaming Set and Guides', '', ARRAY['depuy-synthes','lawton']::text[]),
  ('boquet-en-inox-pour-les-salles-operatoires-34', 'instrument', 'autre', 'Boquet En Inox Pour Les Salles Opératoires', 'Stainless Steel Basin for Operating Rooms', '', ARRAY['a2-medical']::text[]),
  ('cable-bipolaire-3m-35', 'instrument', 'cables-electrodes', 'Cable Bipolaire 3m', 'Bipolar Cable, 3m', '', ARRAY['aesculap','bowa','lawton','mcm','nopa']::text[]),
  ('cable-de-lumiere-d4-8-36', 'instrument', 'cables-electrodes', 'Cable De Lumiere D4.8', 'Light Cable, D4.8', '', ARRAY['aesculap','hermann','lawton','mcm','olympus','precisa','rz-medizin']::text[]),
  ('cable-lumiere-37', 'equipment', 'autre', 'Cable Lumiére', 'Light Cable', '', ARRAY['conmed','olympus','precisa','smith-nephew','wolf']::text[]),
  ('cable-monopolaire-38', 'instrument', 'cables-electrodes', 'Cable Monopolaire', 'Monopolar Cable', '', ARRAY['aesculap','bowa','erbe','lawton','mcm','reda','rz-medizin','wolf']::text[]),
  ('cable-monopolaire-erbe-3mm-39', 'instrument', 'cables-electrodes', 'Cable Monopolaire Erbe 3mm', 'Monopolar Cable, Erbe, 3mm', '', ARRAY['aesculap','bowa','erbe']::text[]),
  ('cable-monopolaire-olympus-pour-urologie-40', 'instrument', 'cables-electrodes', 'Cable Monopolaire Olympus Pour Urologie', 'Monopolar Cable, Olympus, for Urology', '', ARRAY['bowa']::text[]),
  ('cables-bipolaire-type-de-connexion-valley-lab-3metre-41', 'instrument', 'cables-electrodes', 'Cables Bipolaire Type De Connexion Valley Lab 3METRE', 'Bipolar Cable, Valleylab-Type Connector, 3m', '', ARRAY['aesculap','bowa','hermann','lawton','mcm','olympus','reda','rz-medizin']::text[]),
  ('cables-monopolaire-3-metre-42', 'instrument', 'cables-electrodes', 'Cables Monopolaire 3 Metre', 'Monopolar Cable, 3m', '', ARRAY['aesculap','bowa','erbe','hermann','lawton','mcm','olympus','reda','rz-medizin']::text[]),
  ('camera-pour-urologie-pendule-43', 'equipment', 'autre', 'Camera Pour Urologie Pendulé', 'Suspended Camera for Urology', '', ARRAY['conmed','olympus']::text[]),
  ('cannule-6mm-double-robinet-rotatif-44', 'instrument', 'aiguilles-canules', 'Cannule 6MM Double Robinet Rotatif', 'Cannula, 6mm, Double Rotating Stopcock', '', ARRAY['lawton','mcm','reda','smith-nephew']::text[]),
  ('cannule-d-aspiration-45', 'instrument', 'aiguilles-canules', 'Cannule D''Aspiration', 'Suction Cannula', '', ARRAY['aesculap','holtex','integra','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('canule-aspiratif-irrigation-46', 'instrument', 'aiguilles-canules', 'Canule Aspiratif + Irrigation', 'Suction/Irrigation Cannula', '', ARRAY['aesculap','lawton','mcm','reda','tontarra']::text[]),
  ('canule-aspiration-47', 'instrument', 'aiguilles-canules', 'Canule Aspiration', 'Suction Cannula', '', ARRAY['lawton','mcm','reda','surgicon']::text[]),
  ('canule-aspiration-18cm-diametre-10mm-90-fergusson-48', 'instrument', 'aiguilles-canules', 'Canule Aspiration 18cm Diametre 10mm 90 Fergusson', 'Suction Cannula, 18cm, 10mm Diameter, 90°, Fergusson', '', ARRAY['lawton','mcm','nopa','reda']::text[]),
  ('canule-aspiration-18cm-diametre-15mm-90-fergusson-49', 'instrument', 'aiguilles-canules', 'Canule Aspiration 18cm Diametre 15mm 90 Fergusson', 'Suction Cannula, 18cm, 15mm Diameter, 90°, Fergusson', '', ARRAY['lawton','mcm','reda']::text[]),
  ('canule-aspiration-18cm-diametre-5mm-90-fergusson-50', 'instrument', 'aiguilles-canules', 'Canule Aspiration 18cm Diametre 5mm 90 Fergusson', 'Suction Cannula, 18cm, 5mm Diameter, 90°, Fergusson', '', ARRAY['lawton','mcm','nopa','reda']::text[]),
  ('canule-aspiration-18cm-diametre-7mm-90-fergusson-51', 'instrument', 'aiguilles-canules', 'Canule Aspiration 18cm Diametre 7mm 90 Fergusson', 'Suction Cannula, 18cm, 7mm Diameter, 90°, Fergusson', '', ARRAY['lawton','mcm','nopa','reda']::text[]),
  ('canule-aspiration-frazier-08-52', 'instrument', 'aiguilles-canules', 'Canule Aspiration Frazier 08', 'Suction Cannula, Frazier, 08', '', ARRAY['lawton','mcm','nopa','reda','surgicon']::text[]),
  ('canule-aspiration-frazier-10-53', 'instrument', 'aiguilles-canules', 'Canule Aspiration Frazier 10', 'Suction Cannula, Frazier, 10', '', ARRAY['lawton','mcm','nopa','reda','surgicon']::text[]),
  ('canule-aspiration-frazier-12-54', 'instrument', 'aiguilles-canules', 'Canule Aspiration Frazier 12', 'Suction Cannula, Frazier, 12', '', ARRAY['lawton','mcm','nopa','reda','surgicon']::text[]),
  ('canule-aspiration-frazier-15-55', 'instrument', 'aiguilles-canules', 'Canule Aspiration Frazier 15', 'Suction Cannula, Frazier, 15', '', ARRAY['lawton','mcm','nopa','reda','surgicon']::text[]),
  ('canule-aspiration-irrigation-a-poignet-diam-5-pour-colio-56', 'instrument', 'aiguilles-canules', 'Canule Aspiration/Irrigation A Poignet Diam 5 Pour Colio', 'Suction/Irrigation Cannula with Handle, 5mm Diameter, for Laparoscopy', '', ARRAY['mcm','rz-medizin','tontarra']::text[]),
  ('canule-d-aspiration-57', 'instrument', 'aiguilles-canules', 'Canule D''Aspiration', 'Suction Cannula', '', ARRAY['aesculap','holtex']::text[]),
  ('canule-d-aspiration-18cm-diametre-10mm-90-fergusson-58', 'instrument', 'aiguilles-canules', 'Canule D''Aspiration 18cm ; Diamètre 10mm, 90° (Fergusson)', 'Suction Cannula, 18cm, 10mm Diameter, 90° (Fergusson)', '', ARRAY['aesculap']::text[]),
  ('canule-d-aspiration-18cm-diametre-15mm-90-fergusson-59', 'instrument', 'aiguilles-canules', 'Canule D''Aspiration 18cm ; Diamètre 15mm, 90° (Fergusson)', 'Suction Cannula, 18cm, 15mm Diameter, 90° (Fergusson)', '', ARRAY['aesculap']::text[]),
  ('canule-d-aspiration-18cm-diametre-5mm-90-fergusson-60', 'instrument', 'aiguilles-canules', 'Canule D''Aspiration 18cm ; Diamètre 5mm, 90° (Fergusson)', 'Suction Cannula, 18cm, 5mm Diameter, 90° (Fergusson)', '', ARRAY['aesculap']::text[]),
  ('canule-d-aspiration-18cm-diametre-7mm-90-fergusson-61', 'instrument', 'aiguilles-canules', 'Canule D''Aspiration 18cm ; Diamètre 7mm, 90° (Fergusson)', 'Suction Cannula, 18cm, 7mm Diameter, 90° (Fergusson)', '', ARRAY['aesculap']::text[]),
  ('canule-d-aspiration-de-frazier-08-62', 'instrument', 'aiguilles-canules', 'Canule D''Aspiration De Frazier ° 08', 'Suction Cannula, Frazier, 08', '', ARRAY['aesculap','integra']::text[]),
  ('canule-d-aspiration-de-frazier-10-63', 'instrument', 'aiguilles-canules', 'Canule D''Aspiration De Frazier ° 10', 'Suction Cannula, Frazier, 10', '', ARRAY['aesculap','integra']::text[]),
  ('canule-d-aspiration-de-frazier-12-64', 'instrument', 'aiguilles-canules', 'Canule D''Aspiration De Frazier ° 12', 'Suction Cannula, Frazier, 12', '', ARRAY['aesculap','integra']::text[]),
  ('canule-d-aspiration-de-frazier-15-65', 'instrument', 'aiguilles-canules', 'Canule D''Aspiration De Frazier ° 15', 'Suction Cannula, Frazier, 15', '', ARRAY['aesculap','integra']::text[]),
  ('canule-d-aspiration-irrigation-a-poignet-basculant-d5mm-66', 'instrument', 'aiguilles-canules', 'Canule D''Aspiration Irrigation A Poignet Basculant D5mm', 'Suction/Irrigation Cannula with Tilting Handle, D5mm', '', ARRAY['aesculap','hermann','lawton','mcm','olympus','reda','rz-medizin','tontarra']::text[]),
  ('canule-d-aspiration-irrigation-a-poignet-diam-5-pour-colio-67', 'instrument', 'aiguilles-canules', 'Canule D''Aspiration/Irrigation A Poignet Diam 5 Pour Colio', 'Suction/Irrigation Cannula with Handle, 5mm Diameter, for Laparoscopy', '', ARRAY['aesculap']::text[]),
  ('canule-d-aspiration-robinet-68', 'instrument', 'aiguilles-canules', 'Canule D Aspiration / Robinet', 'Suction Cannula / Stopcock', '', ARRAY['aesculap','lawton','tontarra','wolf']::text[]),
  ('canule-d-aspiration-tubes-69', 'instrument', 'aiguilles-canules', 'Canule D Aspiration / Tubes', 'Suction Cannula / Tubes', '', ARRAY['aesculap','lawton','tontarra','wolf']::text[]),
  ('canule-de-lipo-avec-troue-3-25-70', 'instrument', 'aiguilles-canules', 'Canule De Lipo Avec Troue 3/25', 'Liposuction Cannula with Hole, 3/25', '', ARRAY['mcm']::text[]),
  ('canule-de-lipo-avec-troue-4-25-71', 'instrument', 'aiguilles-canules', 'Canule De Lipo Avec Troue 4/25', 'Liposuction Cannula with Hole, 4/25', '', ARRAY['mcm']::text[]),
  ('canule-de-lipo-avec-troue-5-25-72', 'instrument', 'aiguilles-canules', 'Canule De Lipo Avec Troue 5/25', 'Liposuction Cannula with Hole, 5/25', '', ARRAY['mcm']::text[]),
  ('canule-infiltration-pour-irrigation-diam-2l25-73', 'instrument', 'aiguilles-canules', 'Canule Infiltration Pour Irrigation Diam 2L25', 'Infiltration Cannula for Irrigation, Diam 2L25', '', ARRAY['mcm']::text[]),
  ('caspar-bone-curettes-22cm-3-6mm-74', 'instrument', 'autre', 'Caspar Bone Curettes( 22cm,3,6mm )', 'Caspar Bone Curette, 22cm, 3.6mm', '', ARRAY['aesculap','lawton','mcm','precisa','reda']::text[]),
  ('caspar-bone-curettes-22cm-4-4mm-75', 'instrument', 'autre', 'Caspar Bone Curettes(22cm,4,4mm)', 'Caspar Bone Curette, 22cm, 4.4mm', '', ARRAY['aesculap','lawton','mcm','precisa','reda']::text[]),
  ('caspar-bone-curettes-22cm-5-2mm-76', 'instrument', 'autre', 'Caspar Bone Curettes(22cm,5,2mm)', 'Caspar Bone Curette, 22cm, 5.2mm', '', ARRAY['aesculap','lawton','mcm','precisa','reda']::text[]),
  ('castro-porte-aiguille-vasculaire-l15cm-77', 'instrument', 'aiguilles-canules', 'Castro (Porte Aiguille Vasculaire L15cm)', 'Castro Vascular Needle Holder, L15cm', '', ARRAY['aesculap','lawton','mcm','nopa','precisa','reda']::text[]),
  ('castro-porte-aiguille-vasculaire-l23-78', 'instrument', 'aiguilles-canules', 'Castro (Porte Aiguille Vasculaire L23)', 'Castro Vascular Needle Holder, L23', '', ARRAY['aesculap','lawton','mcm','precisa','reda']::text[]),
  ('cavitron-79', 'equipment', 'bloc-operatoire', 'Cavitron', 'Cavitron', '', ARRAY['integra','soring']::text[]),
  ('chaises-patients-avec-reposes-pieds-80', 'equipment', 'autre', 'Chaises Patients Avec Reposes Pieds', 'Patient Chairs with Footrests', '', ARRAY['divers','nitrocare']::text[]),
  ('chariot-brancard-salle-de-reveil-81', 'equipment', 'mobilier-transport', 'Chariot Brancard ( Salle De Réveil)', 'Stretcher Trolley (Recovery Room)', '', ARRAY['bmk','famed','linea-life','medikal','optium','schroder']::text[]),
  ('chariot-d-urgence-82', 'equipment', 'mobilier-transport', 'Chariot D''Urgence', 'Emergency Cart', '', ARRAY['a2-medical','aurion','linea-life','medikal','optium','schroder']::text[]),
  ('chariot-de-soins-83', 'equipment', 'mobilier-transport', 'Chariot De Soins', 'Treatment Cart', '', ARRAY['a2-medical','aurion','linea-life','medikal','optium']::text[]),
  ('chariot-malade-84', 'equipment', 'mobilier-transport', 'Chariot Malade', 'Patient Trolley', '', ARRAY['amel','famed','medikal','nitrocare','optium','schroder']::text[]),
  ('chariot-pour-linges-propre-85', 'equipment', 'mobilier-transport', 'Chariot Pour Linges Propre', 'Trolley for Clean Linen', '', ARRAY['tts']::text[]),
  ('chariot-pour-rangement-panseur-bloc-operatoire-86', 'equipment', 'mobilier-transport', 'Chariot Pour Rangement Panseur Bloc Opératoire', 'Dressing Storage Trolley, Operating Room', '', ARRAY['a2-medical','amel','aurion','linea-life','medikal']::text[]),
  ('chariots-de-transport-malades-87', 'equipment', 'mobilier-transport', 'Chariots De Transport Malades', 'Patient Transport Trolleys', '', ARRAY['amel','famed','linea-life','medikal','schroder']::text[]),
  ('chauffages-pour-patient-88', 'equipment', 'autre', 'Chauffages Pour Patient', 'Patient Warmers', '', ARRAY['3m-bair-hugger','lifotronic']::text[]),
  ('chemise-10-89', 'instrument', 'optiques-endoscopie', 'Chemise 10', 'Sheath, 10', '', ARRAY['lawton','mcm','reda','wolf']::text[]),
  ('chemise-5-5-90', 'instrument', 'optiques-endoscopie', 'Chemise 5.5', 'Sheath, 5.5', '', ARRAY['aesculap','lawton','mcm','reda','wolf']::text[]),
  ('ciseau-coelio-91', 'instrument', 'optiques-endoscopie', 'Ciseau Coelio', 'Laparoscopic Scissors', '', ARRAY['aesculap','lawton','mcm','reda','tontarra','wolf']::text[]),
  ('ciseau-metzembum-30cm-courbe-92', 'instrument', 'ciseaux-coupe', 'Ciseau Metzembum 30cm Courbe', 'Metzenbaum Scissors, Curved, 30cm', '', ARRAY['aesculap','holtex','integra','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('ciseaux-a-droite-93', 'instrument', 'ciseaux-coupe', 'Ciseaux A Droite', 'Scissors, Right', '', ARRAY['lawton','mcm','precisa','reda','smith-nephew']::text[]),
  ('ciseaux-a-dure-mere-taylor-17cm-94', 'instrument', 'ciseaux-coupe', 'Ciseaux À Dure Mère (Taylor) 17cm', 'Taylor Dura Scissors, 17cm', '', ARRAY['aesculap','lawton','mcm','nopa','precisa','reda']::text[]),
  ('ciseaux-coelio-diam-5-l33-courbe-95', 'instrument', 'optiques-endoscopie', 'Ciseaux Coelio Diam 5 L33 Courbe', 'Laparoscopic Scissors, 5mm Diameter, L33, Curved', '', ARRAY['aesculap','lawton','mcm','rz-medizin','tontarra','wolf']::text[]),
  ('ciseaux-de-metzenbaum-mors-12mm-96', 'instrument', 'ciseaux-coupe', 'Ciseaux De Metzenbaum Mors 12mm', 'Metzenbaum Scissors, 12mm Jaw', '', ARRAY['aesculap','hermann','lawton','mcm','olympus','reda','rz-medizin','tontarra','wolf']::text[]),
  ('ciseaux-mayo-courbe-14-cm-97', 'instrument', 'ciseaux-coupe', 'Ciseaux Mayo Courbe 14 cm', 'Mayo Scissors, Curved, 14cm', '', ARRAY['aesculap','holtex','integra','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('ciseaux-mayo-courbe-17-cm-98', 'instrument', 'ciseaux-coupe', 'Ciseaux Mayo Courbe 17 cm', 'Mayo Scissors, Curved, 17cm', '', ARRAY['aesculap','holtex','integra','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('ciseaux-mayo-courbe-20-cm-99', 'instrument', 'ciseaux-coupe', 'Ciseaux Mayo Courbe 20 cm', 'Mayo Scissors, Curved, 20cm', '', ARRAY['aesculap','holtex','integra','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('ciseaux-metez-courbe-14-cm-100', 'instrument', 'ciseaux-coupe', 'Ciseaux Metez Courbe 14 cm', 'Metzenbaum Scissors, Curved, 14cm', '', ARRAY['aesculap','holtex','integra','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('ciseaux-metez-courbe-18-cm-101', 'instrument', 'ciseaux-coupe', 'Ciseaux Metez Courbe 18 cm', 'Metzenbaum Scissors, Curved, 18cm', '', ARRAY['aesculap','holtex','integra','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('ciseaux-metez-courbe-20-cm-102', 'instrument', 'ciseaux-coupe', 'Ciseaux Metez Courbe 20 cm', 'Metzenbaum Scissors, Curved, 20cm', '', ARRAY['aesculap','holtex','integra','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('ciseaux-metez-courbe-23-cm-103', 'instrument', 'ciseaux-coupe', 'Ciseaux Metez Courbe 23 cm', 'Metzenbaum Scissors, Curved, 23cm', '', ARRAY['aesculap','holtex','integra','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('ciseaux-metz-courbe-18-cm-104', 'instrument', 'ciseaux-coupe', 'Ciseaux Metz Courbe 18 cm', 'Metzenbaum Scissors, Curved, 18cm', '', ARRAY['aesculap','holtex','integra','lawton','mcm','nopa','precisa','reda']::text[]),
  ('ciseaux-vers-la-droite-105', 'instrument', 'ciseaux-coupe', 'Ciseaux Vers La Droite', 'Scissors, Right', '', ARRAY['lawton','mcm','precisa','reda','smith-nephew']::text[]),
  ('ciseaux-vers-la-gauche-106', 'instrument', 'ciseaux-coupe', 'Ciseaux Vers La Gauche', 'Scissors, Left', '', ARRAY['lawton','mcm','precisa','reda','smith-nephew']::text[]),
  ('cle-pour-moteur-107', 'instrument', 'autre', 'Cle Pour Moteur', 'Motor Key', '', ARRAY['lawton']::text[]),
  ('colonne-endoscopie-moniteur-chariot-processeur-hd-generateur-lumiere-coloscope-fibroscope-108', 'equipment', 'imagerie', 'Colonne Endoscopie (Moniteur+Chariot+Processeur Hd +Génerateur Lumiere +Coloscope +Fibroscope)', 'Endoscopy Tower (Monitor + Trolley + HD Processor + Light Source + Colonoscope + Fibroscope)', '', ARRAY['fujifilm','olympus','smith-nephew','sonoscape','wolf']::text[]),
  ('console-ipc-et-garrot-ats3000-111', 'equipment', 'bloc-operatoire', 'Console Ipc Et Garrot Ats3000', 'IPC Console and Tourniquet, ATS3000', '', ARRAY['ds-mareef','zimmerbiomet']::text[]),
  ('conteneur-pour-boite-micro-chirurgie-avec-tapis-silicone-113', 'instrument', 'autre', 'Conteneur Pour Boite Micro Chirurgie (Avec Tapis Silicone)', 'Container for Microsurgery Set (with Silicone Mat)', '', ARRAY['aesculap','aygun','lawton','mcm','reda']::text[]),
  ('coupe-broche-114', 'instrument', 'ciseaux-coupe', 'Coupe Broche', 'Wire/Pin Cutter', '', ARRAY['aesculap','holtex','lawton','mcm','precisa']::text[]),
  ('craniotome-neuro-115', 'equipment', 'bloc-operatoire', 'Craniotome (Neuro )', 'Craniotome (Neurosurgery)', '', ARRAY['aesculap','conmed','medtronic','novag']::text[]),
  ('cripine-aspiration-faizer-diametre-6-116', 'instrument', 'autre', 'Cripine Aspiration Faizer Diametre 6', 'Frazier Suction Tip, 6mm Diameter', '', ARRAY['mcm','nopa','reda','surgicon']::text[]),
  ('cripine-d-aspiration-faizer-diametre-6-117', 'instrument', 'autre', 'Cripine D''Aspiration Faizer Diamètre 6', 'Frazier Suction Tip, 6mm Diameter', '', ARRAY['aesculap']::text[]),
  ('crochet-ceramique-118', 'instrument', 'ecarteurs', 'Crochet Ceramique', 'Ceramic Hook', '', ARRAY['aesculap','lawton','tontarra']::text[]),
  ('crochet-cushing-18cm-119', 'instrument', 'ecarteurs', 'Crochet Cushing 18cm', 'Cushing Hook, 18cm', '', ARRAY['aesculap','lawton','mcm','nopa','precisa','reda']::text[]),
  ('crochet-dandy-mousse-courbe-22-cm-120', 'instrument', 'ecarteurs', 'Crochet Dandy Mousse Courbe 22 cm', 'Dandy Hook, Blunt, Curved, 22cm', '', ARRAY['aesculap','lawton','mcm','reda','surgicon']::text[]),
  ('crochet-dandy-mousse-droit-20-cm-121', 'instrument', 'ecarteurs', 'Crochet Dandy Mousse Droit 20 cm', 'Dandy Hook, Blunt, Straight, 20cm', '', ARRAY['aesculap','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('crochet-hook-musse-122', 'instrument', 'ecarteurs', 'Crochet Hook Musse', 'Blunt Hook', '', ARRAY['aesculap','integra','lawton','mcm','precisa','reda']::text[]),
  ('crochet-mousse-droite-123', 'instrument', 'ecarteurs', 'Crochet Mousse Droite', 'Blunt Hook, Straight', '', ARRAY['aesculap','lawton','mcm','reda','tontarra']::text[]),
  ('crochets-en-l-diametre-05mm-124', 'instrument', 'ecarteurs', 'Crochets En L Diametre 05mm', 'L-Shaped Hooks, 05mm Diameter', '', ARRAY['aesculap','hermann','lawton','mcm','olympus','reda','rz-medizin','tontarra']::text[]),
  ('cupule-125', 'instrument', 'autre', 'Cupule', 'Cup', '', ARRAY['aesculap','lawton','nopa','reda','surgicon']::text[]),
  ('cupule-15-cc-126', 'instrument', 'autre', 'Cupule 15 Cc', 'Cup, 15cc', '', ARRAY['aesculap','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('cupule-225-cc-127', 'instrument', 'autre', 'Cupule 225 Cc', 'Cup, 225cc', '', ARRAY['aesculap','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('cupule-75-cc-128', 'instrument', 'autre', 'Cupule 75 Cc', 'Cup, 75cc', '', ARRAY['aesculap','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('curette-00-129', 'instrument', 'autre', 'Curette 00', 'Curette, 00', '', ARRAY['aesculap','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('curette-1-130', 'instrument', 'autre', 'Curette 1', 'Curette, 1', '', ARRAY['aesculap','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('curette-2-131', 'instrument', 'autre', 'Curette 2', 'Curette, 2', '', ARRAY['aesculap','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('curette-3-132', 'instrument', 'autre', 'Curette 3', 'Curette, 3', '', ARRAY['aesculap','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('defibrilateur-basic-et-complet-134', 'equipment', 'reanimation', 'Defibrilateur (Basic Et Complet)', 'Defibrillator (Basic and Complete)', '', ARRAY['comen','innomed','mindray','philips','primedic','schiller']::text[]),
  ('dissecteur-angle-droit-diam-10mm-135', 'instrument', 'autre', 'Dissecteur Angle Droit Diam 10mm', 'Right-Angle Dissector, 10mm Diameter', '', ARRAY['aesculap','hermann','lawton','mcm','olympus','reda','rz-medizin','tontarra']::text[]),
  ('dmo-osteo-densito-metrie-appareil-lunar-dpx-136', 'equipment', 'autre', 'Dmo Osteo-Densito-Metrie Appareil Lunar Dpx', 'Bone Densitometry (DMO) Unit, Lunar DPX', '', ARRAY['osteosys']::text[]),
  ('dmo-osteo-densito-metrie-l-appareil-lunar-dpx-137', 'equipment', 'autre', 'Dmo Osteo-Densito-Metrie L''Appareil Lunar Dpx', 'Bone Densitometry (DMO) Unit, the Lunar DPX', 'PRODIGY ADVANCE', ARRAY['dms-stratos','hologic']::text[]),
  ('ecareteur-autostatique-mm-pointu-138', 'instrument', 'autre', 'Ecareteur Autostatique mm Pointu', 'Self-Retaining Retractor, Sharp', '', ARRAY['aesculap','holtex','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('ecarteur-a-bec-139', 'instrument', 'ecarteurs', 'Ecarteur À Bec', 'Beak Retractor', '', ARRAY['holtex','lawton','mcm','precisa','reda']::text[]),
  ('ecarteur-autostatique-weitlaner-17-cm-140', 'instrument', 'ecarteurs', 'Ecarteur Autostatique Weitlaner 17 cm', 'Weitlaner Self-Retaining Retractor, 17cm', '', ARRAY['aesculap','holtex','integra','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('ecarteur-de-carpentier-141', 'instrument', 'ecarteurs', 'Ecarteur De Carpentier', 'Carpentier Retractor', '', ARRAY['mcm','precisa','reda']::text[]),
  ('ecarteur-de-farabeuf-14-cm-142', 'instrument', 'ecarteurs', 'Ecarteur De Farabeuf 14 cm', 'Farabeuf Retractor, 14cm', '', ARRAY['aesculap','holtex','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('ecarteur-de-farabeuf-gm-143', 'instrument', 'ecarteurs', 'Ecarteur De Farabeuf Gm', 'Farabeuf Retractor, Large', '', ARRAY['aesculap','holtex','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('ecarteur-en-z-pour-rhino-144', 'instrument', 'ecarteurs', 'Ecarteur En Z Pour Rhino', 'Z-Retractor for Rhinoplasty', '', ARRAY['mcm','precisa','reda']::text[]),
  ('ecarteur-langenbek-14-70-145', 'instrument', 'ecarteurs', 'Ecarteur Langenbek 14 * 70', 'Langenbeck Retractor, 14x70', '', ARRAY['aesculap','holtex']::text[]),
  ('ecarteur-langenbek-14-x-70-146', 'instrument', 'ecarteurs', 'Ecarteur Langenbek 14 X 70', 'Langenbeck Retractor, 14x70', '', ARRAY['lawton','mcm','nopa','reda','surgicon']::text[]),
  ('ecarteur-langenbek-60-20-147', 'instrument', 'ecarteurs', 'Ecarteur Langenbek 60 * 20', 'Langenbeck Retractor, 60x20', '', ARRAY['aesculap','holtex']::text[]),
  ('ecarteur-langenbek-60-x-20-148', 'instrument', 'ecarteurs', 'Ecarteur Langenbek 60 X 20', 'Langenbeck Retractor, 60x20', '', ARRAY['lawton','mcm','nopa','reda','surgicon']::text[]),
  ('ecarteur-lateral-a-crochet-gauche-149', 'instrument', 'ecarteurs', 'Ecarteur Latéral À Crochet Gauche', 'Lateral Retractor with Left Hook', '', ARRAY['aesculap','lawton','mcm','precisa']::text[]),
  ('ecarteur-sur-manche-obwegeser-courbe-150', 'instrument', 'ecarteurs', 'Ecarteur Sur Manche Obwegeser Courbe', 'Obwegeser Retractor on Handle, Curved', '', ARRAY['aesculap','lawton','mcm','reda','surgicon']::text[]),
  ('ecg-151', 'equipment', 'monitoring', 'Ecg', 'ECG', 'MAC 2000', ARRAY['blt','edan','ge','mindray','philips','schiller']::text[]),
  ('echange-colonne-ceolio-152', 'equipment', 'bloc-operatoire', 'Echange Colonne Ceolio', 'Laparoscopy Tower Replacement', '', ARRAY['conmed','olympus','smith-nephew']::text[]),
  ('echographe-en-remplacement-de-logic-e9-153', 'equipment', 'imagerie', 'Echographe En Remplacement De Logic E9', 'Ultrasound Machine, Replacement for Logiq E9', 'LOGIQ E10S', ARRAY['ge','hitachi','philips','samsung','siemens','sonoscape']::text[]),
  ('echographe-en-remplacement-de-voluson-e8-154', 'equipment', 'imagerie', 'Echographe En Remplacement De Voluson E8', 'Ultrasound Machine, Replacement for Voluson E8', 'VOLUSON E8', ARRAY['ge','hitachi','philips','samsung','siemens','sonoscape']::text[]),
  ('echographe-en-remplacement-du-vivid-7-155', 'equipment', 'imagerie', 'Echographe En Remplacement Du Vivid 7', 'Ultrasound Machine, Replacement for Vivid 7', 'VIVID S70', ARRAY['ge','hitachi','philips','samsung','sonoscape']::text[]),
  ('electrode-de-coagulation-156', 'instrument', 'cables-electrodes', 'Electrode De Coagulation', 'Coagulation Electrode', '', ARRAY['lawton','mcm','reda','tontarra']::text[]),
  ('element-de-travail-actif-pour-resection-157', 'instrument', 'optiques-endoscopie', 'Element De Travail Actif Pour Resection', 'Active Working Element for Resection', '', ARRAY['lawton','rz-medizin','tontarra']::text[]),
  ('element-passif-pistolet-urologie-158', 'instrument', 'autre', 'Element Passif Pistolet Urologie', 'Passive Element, Urology Pistol Grip', '', ARRAY['lawton','tontarra']::text[]),
  ('element-pour-uretrotomie-olympus-avec-gaine-externe-gaine-interne-et-obturateur-159', 'instrument', 'optiques-endoscopie', 'Element Pour Uretrotomie Olympus Avec Gaine Externe Gaine Interne Et Obturateur', 'Urethrotomy Element, Olympus, with Outer Sheath, Inner Sheath and Obturator', '', ARRAY['lawton','tontarra']::text[]),
  ('epingle-de-bunt-pour-instruments-160', 'instrument', 'autre', 'Epingle De Bunt Pour Instruments', 'Bunt Pin for Instruments', '', ARRAY['aesculap','holtex','lawton','mcm','reda']::text[]),
  ('fibroscope-therapeutique-1t-161', 'equipment', 'autre', 'Fibroscope Therapeutique 1T', 'Therapeutic Fibroscope, 1T', '', ARRAY['olympus']::text[]),
  ('gaine-pour-coelio-162', 'instrument', 'optiques-endoscopie', 'Gaine Pour Coelio', 'Sheath for Laparoscopy', '', ARRAY['lawton','tontarra','wolf']::text[]),
  ('gaine-pour-porte-aiguille-163', 'instrument', 'optiques-endoscopie', 'Gaine Pour Porte Aiguille', 'Sheath for Needle Holder', '', ARRAY['lawton']::text[]),
  ('garrot-electrique-double-sortie-164', 'equipment', 'bloc-operatoire', 'Garrot Éléctrique Double Sortie', 'Electric Tourniquet, Dual Outlet', '', ARRAY['dessilons','ds-mareef','zimmerbiomet']::text[]),
  ('garrot-pneumatique-membre-inferieur-165', 'equipment', 'bloc-operatoire', 'Garrot Pneumatique Membre Inferieur', 'Pneumatic Tourniquet, Lower Limb', '', ARRAY['divers','riester','zimmerbiomet']::text[]),
  ('garrot-pneumatique-membre-superieur-166', 'equipment', 'bloc-operatoire', 'Garrot Pneumatique Membre Superieur', 'Pneumatic Tourniquet, Upper Limb', '', ARRAY['divers','riester','zimmerbiomet']::text[]),
  ('gastroscope-fibroscope-167', 'equipment', 'autre', 'Gastroscope (Fibroscope)', 'Gastroscope (Fiberscope)', '', ARRAY['fujifilm','olympus']::text[]),
  ('generateur-de-lumiere-168', 'equipment', 'autre', 'Générateur De Lumiére', 'Light Source Generator', '', ARRAY['conmed','ilo','smith-nephew','wolf']::text[]),
  ('generateur-processeur-olympus-evis-exera-iii-190-169', 'equipment', 'bloc-operatoire', 'Generateur Processeur Olympus Evis Exera Iii 190', 'Generator/Processor, Olympus Evis Exera III 190', '', ARRAY['olympus','sonoscape']::text[]),
  ('gouge-18cm-5mm-170', 'instrument', 'autre', 'Gouge 18cm ; 5mm', 'Gouge, 18cm, 5mm', '', ARRAY['aesculap','holtex','lawton','mcm','nopa','precisa','reda']::text[]),
  ('gueridon-en-inox-pour-salle-de-cathe-171', 'equipment', 'autre', 'Gueridon En Inox Pour Salle De Cathé', 'Stainless Steel Side Table for Cath Lab', '', ARRAY['amel']::text[]),
  ('holter-rythmique-172', 'equipment', 'monitoring', 'Holter Rythmique', 'Holter Monitor (Cardiac Rhythm)', 'SEER 1000', ARRAY['edan','firstmed','schiller']::text[]),
  ('holter-tensionnel-173', 'equipment', 'monitoring', 'Holter Tensionnel', 'Ambulatory Blood Pressure Monitor (Holter)', 'TONOPORT', ARRAY['edan','firstmed','getemed','schiller']::text[]),
  ('insert-ciseaux-175', 'instrument', 'ciseaux-coupe', 'Insert Ciseaux', 'Scissors Insert', '', ARRAY['lawton','tontarra','wolf']::text[]),
  ('insert-fenetre-176', 'instrument', 'autre', 'Insert Fenetre', 'Fenestrated Insert', '', ARRAY['lawton','tontarra','wolf']::text[]),
  ('insert-porte-aiguille-177', 'instrument', 'aiguilles-canules', 'Insert Porte Aiguille', 'Needle Holder Insert', '', ARRAY['aesculap','lawton','tontarra']::text[]),
  ('instrument-pour-vis-cassee-7-pieces-178', 'instrument', 'autre', 'Instrument Pour Vis Cassee 7 Pieces', 'Broken Screw Removal Instrument Set, 7 Pieces', '', ARRAY['lawton','mcm']::text[]),
  ('joint-de-11-mm-pour-trocard-coelio-179', 'instrument', 'optiques-endoscopie', 'Joint De 11 mm Pour Trocard Coelio', 'Seal, 11mm, for Laparoscopic Trocar', '', ARRAY['ackerma','lawton','mcm','reda','rz-medizin','tontarra']::text[]),
  ('joint-de-5mm-pour-trocard-coelio-180', 'instrument', 'optiques-endoscopie', 'Joint De 5mm Pour Trocard Coelio', 'Seal, 5mm, for Laparoscopic Trocar', '', ARRAY['ackerma','lawton','mcm','reda','rz-medizin','tontarra']::text[]),
  ('joint-externe-diamatre-5-10-181', 'instrument', 'autre', 'Joint Externe Diamatre 5-10', 'External Seal, 5-10mm Diameter', '', ARRAY['ackerma','lawton','mcm','precisa']::text[]),
  ('joint-interne-diamatre-5-10-182', 'instrument', 'autre', 'Joint Interne Diamatre 5-10', 'Internal Seal, 5-10mm Diameter', '', ARRAY['ackerma','lawton','mcm','precisa']::text[]),
  ('joints-de-11mm-183', 'instrument', 'autre', 'Joints De 11mm', 'Seals, 11mm', '', ARRAY['ackerma','hermann','lawton','mcm','olympus','precisa','reda','rz-medizin']::text[]),
  ('joints-de-5mm-184', 'instrument', 'autre', 'Joints De 5mm', 'Seals, 5mm', '', ARRAY['ackerma','hermann','lawton','mcm','olympus','precisa','reda','rz-medizin']::text[]),
  ('kerisson-18cm-40-3mm-185', 'instrument', 'autre', 'Kérisson 18cm ; 40° ; 3mm', 'Kerrison Rongeur, 18cm, 40°, 3mm', '', ARRAY['aesculap','lawton','mcm','precisa','reda']::text[]),
  ('kerisson-up-2mm-186', 'instrument', 'autre', 'Kerisson Up (2mm)', 'Kerrison Rongeur, Up, 2mm', '', ARRAY['aesculap','integra','lawton','mcm','nopa','precisa','reda']::text[]),
  ('kerisson-up-3mm-187', 'instrument', 'autre', 'Kerisson Up (3mm)', 'Kerrison Rongeur, Up, 3mm', '', ARRAY['aesculap','integra','lawton','mcm','nopa','precisa','reda']::text[]),
  ('kerisson-up-4mm-188', 'instrument', 'autre', 'Kerisson Up (4mm)', 'Kerrison Rongeur, Up, 4mm', '', ARRAY['aesculap','integra','lawton','mcm','nopa','precisa','reda']::text[]),
  ('kerisson-up-5mm-189', 'instrument', 'autre', 'Kerisson Up (5mm)', 'Kerrison Rongeur, Up, 5mm', '', ARRAY['aesculap','integra','lawton','mcm','nopa','precisa','reda']::text[]),
  ('la-meme-variante-vaccuson-60-190', 'equipment', 'autre', 'La Meme Variante Vaccuson 60', 'Same Variant, Vacuson 60', '', ARRAY['novag']::text[]),
  ('lame-pour-sternotome-191', 'instrument', 'ciseaux-coupe', 'Lame Pour Sternotome', 'Blade for Sternotome', '', ARRAY['aesculap','lawton']::text[]),
  ('lame-pour-uretrotome-192', 'instrument', 'ciseaux-coupe', 'Lame Pour Uretrotome', 'Blade for Urethrotome', '', ARRAY['mcm','tontarra']::text[]),
  ('lames-malleable-12-x200mm-193', 'instrument', 'autre', 'Lames Malléable 12 x200mm', 'Malleable Retractor, 12x200mm', '', ARRAY['aesculap','holtex','lawton','mcm','nopa','precisa','reda']::text[]),
  ('laryngoscope-194', 'equipment', 'autre', 'Laryngoscope', 'Laryngoscope', '', ARRAY['kawe']::text[]),
  ('lit-malade-de-reanimation-196', 'equipment', 'mobilier-transport', 'Lit Malade De Réanimation', 'ICU Patient Bed', '', ARRAY['famed','hillrom','linea-life','linet','medikal','optium','schroder']::text[]),
  ('lithoclast-197', 'equipment', 'bloc-operatoire', 'Lithoclast', 'Lithoclast', '', ARRAY['ems','olympus','wolf']::text[]),
  ('lits-medicalises-198', 'equipment', 'mobilier-transport', 'Lits Médicalisés', 'Medical Beds', '', ARRAY['a2-medical','amel','bmk','famed','hillrom','linea-life','medikal','mespa','nitrocare','schroder']::text[]),
  ('machine-d-hemodiafiltration-continue-199', 'equipment', 'autre', 'Machine D''Hemodiafiltration Continue', 'Continuous Hemodiafiltration Machine', '', ARRAY['fresenius']::text[]),
  ('mammographie-modele-standard-appareil-sonagraphe-800t-200', 'equipment', 'imagerie', 'Mammographie Modele Standard Appareil Sonagraphe 800T', 'Mammography Unit, Standard Model, Sonographe 800T', '', ARRAY['senocrystalnova']::text[]),
  ('mammographie-modele-standard-l-appareil-sonagraphe-800t-201', 'equipment', 'imagerie', 'Mammographie (Modèle Standard) L''Appareil Sonagraphe 800T', 'Mammography Unit, Standard Model, the Sonographe 800T', '', ARRAY['bemems','giotto','hologic','italray','metaltronic']::text[]),
  ('manche-avec-creamailleur-202', 'instrument', 'autre', 'Manche Avec Creamailleur', 'Handle with Ratchet', '', ARRAY['lawton','tontarra','wolf']::text[]),
  ('manche-de-bestouri-n4-203', 'instrument', 'autre', 'Manche De Bestouri N°4', 'Scalpel Handle No. 4', '', ARRAY['aesculap','holtex','integra','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('manche-de-bistouri-n3-l-204', 'instrument', 'ciseaux-coupe', 'Manche De Bistouri N°3 L', 'Scalpel Handle No. 3, Long', '', ARRAY['aesculap','holtex','integra','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('manche-de-bistouri-n3-longue-205', 'instrument', 'ciseaux-coupe', 'Manche De Bistouri N°3 Longue', 'Scalpel Handle No. 3, Long', '', ARRAY['aesculap','holtex','integra','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('manche-de-bistouri-n4-l-206', 'instrument', 'ciseaux-coupe', 'Manche De Bistouri N°4 L', 'Scalpel Handle No. 4, Long', '', ARRAY['aesculap','holtex','integra','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('manche-de-bistouri-n7-207', 'instrument', 'ciseaux-coupe', 'Manche De Bistouri N°7', 'Scalpel Handle No. 7', '', ARRAY['aesculap','integra','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('manche-lame-n4-208', 'instrument', 'ciseaux-coupe', 'Manche Lame N°4', 'Blade Handle No. 4', '', ARRAY['aesculap','holtex','integra','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('manche-sans-cremailleur-209', 'instrument', 'autre', 'Manche Sans Cremailleur', 'Handle without Ratchet', '', ARRAY['lawton','tontarra','wolf']::text[]),
  ('mandrin-10-211', 'instrument', 'autre', 'Mandrin 10', 'Obturator, 10', '', ARRAY['lawton','mcm','precisa','reda','tontarra','wolf']::text[]),
  ('mandrin-11-212', 'instrument', 'autre', 'Mandrin 11', 'Obturator, 11', '', ARRAY['lawton','precisa','rz-medizin','wolf']::text[]),
  ('mandrin-5-213', 'instrument', 'autre', 'Mandrin 5', 'Obturator, 5', '', ARRAY['lawton','precisa','wolf']::text[]),
  ('mandrin-5-5-214', 'instrument', 'autre', 'Mandrin 5.5', 'Obturator, 5.5', '', ARRAY['lawton','mcm','precisa','reda','rz-medizin','tontarra','wolf']::text[]),
  ('mandrin-pour-gaine-cystonephroscopie-215', 'instrument', 'optiques-endoscopie', 'Mandrin Pour Gaine Cystonephroscopie', 'Obturator for Cystonephroscopy Sheath', '', ARRAY['lawton']::text[]),
  ('matelas-alternating-216', 'equipment', 'mobilier-transport', 'Matelas Alternating', 'Alternating Pressure Mattress', '', ARRAY['fazzini','yong-won']::text[]),
  ('matelas-de-transfert-malade-217', 'equipment', 'mobilier-transport', 'Matelas De Transfert Malade', 'Patient Transfer Mattress', '', ARRAY['hillrom']::text[]),
  ('matelas-des-lits-de-reanimation-orthopedique-218', 'equipment', 'reanimation', 'Matelas Des Lits De Reanimation Orthopedique', 'Mattress for Orthopedic ICU Beds', '', ARRAY['famed','hillrom']::text[]),
  ('metzenbaum-fino-sciss-145mm-219', 'instrument', 'autre', 'Metzenbaum Fino Sciss (145mm)', 'Metzenbaum Scissors, Fine, 145mm', '', ARRAY['aesculap','holtex','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('metzenbaum-fino-sciss-180mm-220', 'instrument', 'autre', 'Metzenbaum Fino Sciss (180mm)', 'Metzenbaum Scissors, Fine, 180mm', '', ARRAY['aesculap','holtex','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('micro-moteur-piece-a-main-longue-pour-la-chirurgie-fine-maxilo-orl-221', 'equipment', 'bloc-operatoire', 'Micro Moteur+Piece A Main (Longue ) Pour La Chirurgie Fine Maxilo, Orl', 'Micromotor + Long Handpiece for Fine Maxillofacial/ENT Surgery', '', ARRAY['conmed','huidamed','medtronic','novag']::text[]),
  ('mise-a-niveau-de-la-colonne-pour-urologie-222', 'equipment', 'bloc-operatoire', 'Mise A Niveau De La Colonne Pour Urologie', 'Upgrade Kit for Urology Tower', '', ARRAY['olympus']::text[]),
  ('mondrin-jacob-223', 'instrument', 'autre', 'Mondrin Jacob', 'Jacobs Obturator', '', ARRAY['lawton']::text[]),
  ('moniteurs-de-surveillance-avec-pi-224', 'equipment', 'monitoring', 'Moniteurs De Surveillance Avec Pi', 'Patient Monitors with Invasive Pressure Monitoring', '', ARRAY['b125','biocare','blt','comen','creative','drager','edan','konsung','mindray','nihon-koden','philips']::text[]),
  ('moniteurs-de-transport-225', 'equipment', 'monitoring', 'Moniteurs De Transport', 'Transport Monitors', '', ARRAY['biocare','blt','creative','edan','mindray']::text[]),
  ('moteur-d-irrigation-227', 'equipment', 'bloc-operatoire', 'Moteur D Irrigation', 'Irrigation Pump', '', ARRAY['novag']::text[]),
  ('moteur-et-scie-avec-batterie-pour-orthopedie-228', 'equipment', 'bloc-operatoire', 'Moteur Et Scie Avec Batterie Pour Orthopédie', 'Motor and Saw with Battery, for Orthopedics', '', ARRAY['aesculap','chine','conmed','depy','microaire','novag','zimmerbiomet']::text[]),
  ('neuronavigation-229', 'equipment', 'bloc-operatoire', 'Neuronavigation', 'Neuronavigation System', '', ARRAY['brainlab','integra']::text[]),
  ('neurostimulateur-230', 'equipment', 'bloc-operatoire', 'Neurostimulateur', 'Neurostimulator', '', ARRAY['brawn','cefar-compex','inomed']::text[]),
  ('nutripompe-232', 'equipment', 'autre', 'Nutripompe', 'Feeding Pump', '', ARRAY['hawkmed','medcaptain']::text[]),
  ('obturateur-233', 'instrument', 'autre', 'Obturateur', 'Obturator', '', ARRAY['mcm','reda','smith-nephew']::text[]),
  ('optiflow-avec-accessoire-et-assistance-respiratoire-235', 'equipment', 'reanimation', 'Optiflow Avec Accessoire Et Assistance Réspiratoire', 'Optiflow with Accessories and Respiratory Support', '', ARRAY['bmc-medical','capnomed','comen','f-p','heyer','lowentein','tni']::text[]),
  ('optique-0-diametre-5-pour-coelio-236', 'instrument', 'optiques-endoscopie', 'Optique 0°, Diamètre 5 Pour Coelio', 'Laparoscope, 0°, 5mm Diameter', '', ARRAY['aesculap','covidien','lawton','mcm','nopa','olympus','reda','tontarra']::text[]),
  ('optique-30-arthroscopie-237', 'instrument', 'optiques-endoscopie', 'Optique 30° Arthroscopie', 'Arthroscope, 30°', '', ARRAY['endolook','lawton','mcm','nopa','precisa','reda']::text[]),
  ('optique-30-diametre-10-pour-coelio-238', 'instrument', 'optiques-endoscopie', 'Optique 30° Diametre 10 Pour Coelio', 'Laparoscope, 30°, 10mm Diameter', '', ARRAY['aesculap','covidien','lawton','mcm','nopa','olympus','tontarra']::text[]),
  ('optique-30-diametre-4-pour-coelio-239', 'instrument', 'optiques-endoscopie', 'Optique 30°, Diamètre 4 Pour Coelio', 'Laparoscope, 30°, 4mm Diameter', '', ARRAY['aesculap','endolook','lawton','mcm','nopa','olympus','reda','tontarra']::text[]),
  ('optique-autoclavable-4mm-30-hd-240', 'instrument', 'optiques-endoscopie', 'Optique Autoclavable 4MM, 30° Hd', 'Autoclavable Scope, 4mm, 30°, HD', '', ARRAY['endolook','lawton','mcm','precisa','reda','smith-nephew']::text[]),
  ('optique-diam-4-l30-30-241', 'instrument', 'optiques-endoscopie', 'Optique Diam 4 L30 30°', 'Scope, 4mm Diameter, L30, 30°', '', ARRAY['aesculap','endolook','lawton','mcm','nopa','reda','tontarra']::text[]),
  ('optique-diam-4mm-0-l30cm-242', 'instrument', 'optiques-endoscopie', 'Optique Diam 4mm 0° L30cm', 'Scope, 4mm Diameter, 0°, L30cm', '', ARRAY['aesculap','endolook','lawton','mcm','nopa','reda','tontarra']::text[]),
  ('optique-diam10-0-l30cm-243', 'instrument', 'optiques-endoscopie', 'Optique Diam10 0° L30cm', 'Scope, 10mm Diameter, 0°, L30cm', '', ARRAY['aesculap','covidien','lawton','mcm','nopa','reda','tontarra']::text[]),
  ('osteotome-pour-rhino-a-droite-244', 'instrument', 'autre', 'Ostéotome Pour Rhino A Droite', 'Osteotome for Rhinoplasty, Right', '', ARRAY['aesculap','lawton','mcm','precisa','reda']::text[]),
  ('osteotome-pour-rhino-a-gauche-245', 'instrument', 'autre', 'Ostéotome Pour Rhino A Gauche', 'Osteotome for Rhinoplasty, Left', '', ARRAY['aesculap','lawton','mcm','precisa','reda']::text[]),
  ('palpateur-droit-246', 'instrument', 'autre', 'Palpateur Droit', 'Probe, Straight', '', ARRAY['lawton','precisa','reda','smith-nephew']::text[]),
  ('paravant-pour-la-salle-de-reveil-247', 'equipment', 'autre', 'Paravant Pour La Salle De Reveil', 'Screen for Recovery Room', '', ARRAY['amel']::text[]),
  ('piece-allesage-249', 'instrument', 'autre', 'Piece Allesage', 'Reamer Piece', '', ARRAY['lawton']::text[]),
  ('pied-a-coulisse-250', 'instrument', 'autre', 'Pied A Coulisse', 'Caliper', '', ARRAY['aesculap','lawton','mcm','reda']::text[]),
  ('pince-a-biopsie-diam-5mm-251', 'instrument', 'pinces-prehension', 'Pince A Biopsie Diam 5mm', 'Biopsy Forceps, 5mm Diameter', '', ARRAY['aesculap','hermann','lawton','mcm','olympus','reda','rz-medizin','tontarra']::text[]),
  ('pince-a-calcul-pour-uretheroscopie-252', 'instrument', 'pinces-prehension', 'Pince A Calcul Pour Uretheroscopie', 'Stone Forceps for Ureteroscopy', '', ARRAY['lawton','mcm','reda','rz-medizin','tontarra']::text[]),
  ('pince-a-calcul-urologie-253', 'instrument', 'pinces-prehension', 'Pince A Calcul Urologie', 'Stone Forceps, Urology', '', ARRAY['lawton','mcm','reda','tontarra']::text[]),
  ('pince-a-calcule-flexible-254', 'instrument', 'pinces-prehension', 'Pince A Calcule Flexible', 'Flexible Stone Forceps', '', ARRAY['lawton','mcm','tontarra']::text[]),
  ('pince-a-champs-255', 'instrument', 'pinces-prehension', 'Pince À Champs', 'Towel Clamp', '', ARRAY['aesculap','holtex','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('pince-a-clip-256', 'instrument', 'pinces-prehension', 'Pince A Clip', 'Clip Applier', '', ARRAY['ackerma','aesculap','lawton','mcm','reda','tontarra']::text[]),
  ('pince-a-clip-diam-10meduim-large-257', 'instrument', 'pinces-prehension', 'Pince A Clip Diam 10meduim/Large', 'Clip Applier, 10mm, Medium/Large', '', ARRAY['ackerma','lawton','mcm','precisa','reda','rz-medizin']::text[]),
  ('pince-a-clip-pour-anevrysme-258', 'instrument', 'pinces-prehension', 'Pince A Clip Pour Anevrysme', 'Aneurysm Clip Applier', '', ARRAY['aesculap','mcm','reda']::text[]),
  ('pince-a-clip-pour-coelio-259', 'instrument', 'optiques-endoscopie', 'Pince A Clip Pour Coelio', 'Clip Applier for Laparoscopy', '', ARRAY['aesculap','lawton','precisa','rz-medizin','teleflex']::text[]),
  ('pince-a-disque-1-jeux-5-pieces-260', 'instrument', 'pinces-prehension', 'Pince A Disque / 1 Jeux = 5 Pieces', 'Disc Punch Forceps, Set of 5', '', ARRAY['aesculap','holtex','lawton','mcm','reda']::text[]),
  ('pince-a-disque-droit-2-10mm-long-18-cm-261', 'instrument', 'pinces-prehension', 'Pince À Disque Droit (2*10mm) Long 18 cm', 'Disc Punch Forceps, Straight, 2x10mm, 18cm', '', ARRAY['aesculap','integra']::text[]),
  ('pince-a-disque-droit-2x10mm-long-18-cm-262', 'instrument', 'pinces-prehension', 'Pince A Disque Droit 2x10mm Long 18 cm', 'Disc Punch Forceps, Straight, 2x10mm, 18cm', '', ARRAY['lawton','mcm','reda','surgicon']::text[]),
  ('pince-a-disque-droit-3-10-mm-263', 'instrument', 'pinces-prehension', 'Pince À Disque Droit 3*10 mm', 'Disc Punch Forceps, Straight, 3x10mm', '', ARRAY['aesculap']::text[]),
  ('pince-a-disque-droit-3x10-mm-264', 'instrument', 'pinces-prehension', 'Pince A Disque Droit 3x10 mm', 'Disc Punch Forceps, Straight, 3x10mm', '', ARRAY['lawton','mcm','precisa','reda']::text[]),
  ('pince-a-disque-droit-4-10-mm-265', 'instrument', 'pinces-prehension', 'Pince À Disque Droit 4*10 mm', 'Disc Punch Forceps, Straight, 4x10mm', '', ARRAY['aesculap']::text[]),
  ('pince-a-disque-droit-4x10-mm-266', 'instrument', 'pinces-prehension', 'Pince A Disque Droit 4x10 mm', 'Disc Punch Forceps, Straight, 4x10mm', '', ARRAY['lawton','mcm','precisa','reda']::text[]),
  ('pince-a-disque-kerisson-45-3-mm-long-18-cm-267', 'instrument', 'pinces-prehension', 'Pince À Disque Kerisson 45° 3 mm Long 18 cm', 'Kerrison Disc Punch Forceps, 45°, 3mm, 18cm', '', ARRAY['aesculap','integra','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('pince-a-disque-kerisson-45-4-mm-long-18-cm-268', 'instrument', 'pinces-prehension', 'Pince À Disque Kerisson 45° 4 mm Long 18 cm', 'Kerrison Disc Punch Forceps, 45°, 4mm, 18cm', '', ARRAY['aesculap','integra','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('pince-a-disque-kerisson-haut-3-mm-long-10-cm-269', 'instrument', 'pinces-prehension', 'Pince À Disque Kerisson Haut 3 mm Long 10 cm', 'Kerrison Disc Punch Forceps, Up, 3mm, 10cm', '', ARRAY['aesculap','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('pince-a-disseque-avec-griffe-30cm-270', 'instrument', 'pinces-prehension', 'Pince A Dissequé Avec Griffe 30cm', 'Dissecting Forceps with Teeth, 30cm', '', ARRAY['aesculap','holtex','integra','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('pince-a-disseque-sans-griffe-30cm-271', 'instrument', 'pinces-prehension', 'Pince A Dissequé Sans Griffe 30cm', 'Dissecting Forceps without Teeth, 30cm', '', ARRAY['aesculap','holtex','integra','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('pince-a-dissequer-a-g-18-cm-272', 'instrument', 'pinces-prehension', 'Pince À Dissequer A/G 18 cm', 'Dissecting Forceps, Toothed/Non-Toothed, 18cm', '', ARRAY['aesculap','holtex','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('pince-a-dissequer-adson-a-g-15-cm-273', 'instrument', 'pinces-prehension', 'Pince À Dissequer Adson A/G 15 cm', 'Adson Dissecting Forceps, Toothed/Non-Toothed, 15cm', '', ARRAY['aesculap','holtex','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('pince-a-dissequer-atraumatique-20-cm-274', 'instrument', 'pinces-prehension', 'Pince À Dissequer Atraumatique 20 cm', 'Atraumatic Dissecting Forceps, 20cm', '', ARRAY['aesculap','holtex','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('pince-a-dissequer-de-bakey-a-g-17-cm-275', 'instrument', 'pinces-prehension', 'Pince À Dissequer De Bakey A/G 17 cm', 'DeBakey Dissecting Forceps, Toothed/Non-Toothed, 17cm', '', ARRAY['aesculap','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('pince-a-dissequer-en-bayonet-276', 'instrument', 'pinces-prehension', 'Pince À Dissequer En Bayonet', 'Bayonet Dissecting Forceps', '', ARRAY['aesculap','holtex','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('pince-a-dissequer-fine-277', 'instrument', 'pinces-prehension', 'Pince A Dissequer Fine', 'Fine Dissecting Forceps', '', ARRAY['aesculap','holtex','lawton','mcm','nopa','reda','smith','surgicon']::text[]),
  ('pince-a-dissiquer-dubakey-18-cm-278', 'instrument', 'pinces-prehension', 'Pince A Dissiquer Dubakey 18 cm', 'DeBakey Dissecting Forceps, 18cm', '', ARRAY['aesculap','holtex','lawton','mcm','nopa','precisa','reda']::text[]),
  ('pince-a-tumeur-yasargil-220mm-diametre-5mm-279', 'instrument', 'pinces-prehension', 'Pince À Tumeur Yasargil 220mm ; Diamètre 5mm', 'Yasargil Tumor Forceps, 220mm, 5mm Diameter', '', ARRAY['aesculap','lawton','mcm','precisa','reda']::text[]),
  ('pince-aprehension-olymus-280', 'instrument', 'pinces-prehension', 'Pince Aprehension Olymus', 'Grasping Forceps, Olympus', '', ARRAY['lawton','tontarra']::text[]),
  ('pince-basket-45-courbe-a-droite-281', 'instrument', 'pinces-prehension', 'Pince Basket 45° Courbe A Droite', 'Basket Forceps, 45°, Curved Right', '', ARRAY['aesculap','lawton','precisa','reda','smith-nephew']::text[]),
  ('pince-basket-45-courbe-a-gauche-282', 'instrument', 'pinces-prehension', 'Pince Basket 45° Courbe A Gauche', 'Basket Forceps, 45°, Curved Left', '', ARRAY['aesculap','lawton','precisa','reda','smith-nephew']::text[]),
  ('pince-basket-a-droite-283', 'instrument', 'pinces-prehension', 'Pince Basket A Droite', 'Basket Forceps, Right', '', ARRAY['aesculap','lawton','precisa','reda','smith-nephew']::text[]),
  ('pince-basket-a-droite-vers-le-haut-284', 'instrument', 'pinces-prehension', 'Pince Basket A Droite Vers Le Haut', 'Basket Forceps, Right, Upward', '', ARRAY['aesculap','lawton','precisa','reda','smith-nephew']::text[]),
  ('pince-beingolea-avec-griffe-courbe-26-cm-285', 'instrument', 'pinces-prehension', 'Pince Beingolea Avec Griffe Courbe 26 cm', 'Bengolea Forceps with Teeth, Curved, 26cm', '', ARRAY['aesculap','holtex','integra','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('pince-beingolea-avec-griffe-droit-26-cm-286', 'instrument', 'pinces-prehension', 'Pince Beingolea Avec Griffe Droit 26 cm', 'Bengolea Forceps with Teeth, Straight, 26cm', '', ARRAY['aesculap','holtex','integra','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('pince-beingolea-sans-griffe-courbe-26-cm-287', 'instrument', 'pinces-prehension', 'Pince Beingolea Sans Griffe Courbe 26 cm', 'Bengolea Forceps without Teeth, Curved, 26cm', '', ARRAY['aesculap','holtex','integra','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('pince-beingolea-sans-griffe-droit-26-cm-288', 'instrument', 'pinces-prehension', 'Pince Beingolea Sans Griffe Droit 26 cm', 'Bengolea Forceps without Teeth, Straight, 26cm', '', ARRAY['aesculap','holtex','integra','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('pince-bipolaire-non-stick-289', 'instrument', 'pinces-prehension', 'Pince Bipolaire Non Stick', 'Bipolar Forceps, Non-Stick', '', ARRAY['aesculap','bowa','erbe','lawton','mcm']::text[]),
  ('pince-chapu-15-cm-290', 'instrument', 'pinces-prehension', 'Pince Chapu 15 cm', 'Chaput Forceps, 15cm', '', ARRAY['aesculap','holtex','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('pince-chapu-18-cm-291', 'instrument', 'pinces-prehension', 'Pince Chapu 18 cm', 'Chaput Forceps, 18cm', '', ARRAY['aesculap','lawton','mcm','reda','surgicon']::text[]),
  ('pince-coupante-liston-292', 'instrument', 'pinces-prehension', 'Pince Coupante Liston', 'Liston Bone Cutting Forceps', '', ARRAY['aesculap','holtex','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('pince-coupe-fil-293', 'instrument', 'pinces-prehension', 'Pince Coupe Fil', 'Wire Cutting Forceps', '', ARRAY['lawton','precisa','reda','smith-nephew']::text[]),
  ('pince-crocodille-gm-294', 'instrument', 'pinces-prehension', 'Pince Crocodille Gm', 'Crocodile Forceps, Large', '', ARRAY['aesculap','lawton','mcm','tontarra','wolf']::text[]),
  ('pince-d-ablation-sonde-jj-295', 'instrument', 'pinces-prehension', 'Pince D Ablation Sonde Jj', 'JJ Stent Removal Forceps', '', ARRAY['lawton']::text[]),
  ('pince-de-cushing-296', 'instrument', 'pinces-prehension', 'Pince De Cushing', 'Cushing Forceps', '', ARRAY['aesculap','holtex','lawton','mcm','nopa','reda','rz-medizin','surgicon']::text[]),
  ('pince-dissecteur-297', 'instrument', 'pinces-prehension', 'Pince Dissecteur', 'Dissector Forceps', '', ARRAY['aesculap','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('pince-en-coeur-14-cm-298', 'instrument', 'pinces-prehension', 'Pince En Cœur 14 cm', 'Heart-Shaped Forceps, 14cm', '', ARRAY['aesculap','holtex','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('pince-en-coeur-18-cm-299', 'instrument', 'pinces-prehension', 'Pince En Cœur 18 cm', 'Heart-Shaped Forceps, 18cm', '', ARRAY['aesculap','lawton','mcm','nopa','surgicon']::text[]),
  ('pince-fenetree-300', 'instrument', 'pinces-prehension', 'Pince Fenetree', 'Fenestrated Forceps', '', ARRAY['aesculap','lawton','mcm','reda','tontarra','wolf']::text[]),
  ('pince-first-pass-301', 'instrument', 'pinces-prehension', 'Pince First Pass', 'First Pass Forceps', '', ARRAY['lawton','precisa','reda','smith-nephew']::text[]),
  ('pince-foger-18-cm-302', 'instrument', 'pinces-prehension', 'Pince Foger 18 cm', 'Foerster Forceps, 18cm', '', ARRAY['aesculap','lawton','precisa','reda']::text[]),
  ('pince-gouge-adson-rongeur-303', 'instrument', 'pinces-prehension', 'Pince Gouge Adson Rongeur', 'Adson Rongeur Forceps', '', ARRAY['aesculap','holtex','integra','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('pince-gouge-coudee-19-cm-304', 'instrument', 'pinces-prehension', 'Pince Gouge Coudée 19 cm', 'Gouge Forceps, Angled, 19cm', '', ARRAY['aesculap','holtex','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('pince-gouge-ruskin-18-4-cm-305', 'instrument', 'pinces-prehension', 'Pince Gouge Ruskin 18.4 cm', 'Ruskin Rongeur Forceps, 18.4cm', '', ARRAY['aesculap','holtex','integra','lawton','mcm','nopa','precisa','reda']::text[]),
  ('pince-gouge-simple-306', 'instrument', 'pinces-prehension', 'Pince Gouge Simple', 'Gouge Forceps, Simple', '', ARRAY['aesculap','holtex','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('pince-hemostatique-avec-griffe-12-cm-307', 'instrument', 'pinces-prehension', 'Pince Hemostatique Avec Griffe 12 cm', 'Hemostatic Forceps with Teeth, 12cm', '', ARRAY['aesculap','holtex','integra','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('pince-hemostatique-avec-griffe-15-cm-308', 'instrument', 'pinces-prehension', 'Pince Hemostatique Avec Griffe 15 cm', 'Hemostatic Forceps with Teeth, 15cm', '', ARRAY['aesculap','holtex','integra','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('pince-hemostatique-sans-griffe-12-cm-309', 'instrument', 'pinces-prehension', 'Pince Hemostatique Sans Griffe 12 cm', 'Hemostatic Forceps without Teeth, 12cm', '', ARRAY['aesculap','holtex','integra','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('pince-hemostatique-sans-griffe-15-cm-310', 'instrument', 'pinces-prehension', 'Pince Hemostatique Sans Griffe 15 cm', 'Hemostatic Forceps without Teeth, 15cm', '', ARRAY['aesculap','holtex','integra','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('pince-kerison-2-18-40-311', 'instrument', 'pinces-prehension', 'Pince Kerison (2*18) 40°', 'Kerrison Forceps, 2x18mm, 40°', '', ARRAY['aesculap']::text[]),
  ('pince-kerison-2x18-40-312', 'instrument', 'pinces-prehension', 'Pince Kerison 2x18 40', 'Kerrison Forceps, 2x18mm, 40°', '', ARRAY['lawton','mcm','nopa','precisa','reda']::text[]),
  ('pince-kerison-5-18-40-313', 'instrument', 'pinces-prehension', 'Pince Kerison (5*18) 40°', 'Kerrison Forceps, 5x18mm, 40°', '', ARRAY['aesculap']::text[]),
  ('pince-kerison-5x18-40-314', 'instrument', 'pinces-prehension', 'Pince Kerison 5x18 40', 'Kerrison Forceps, 5x18mm, 40°', '', ARRAY['lawton','mcm','nopa','precisa','reda']::text[]),
  ('pince-kerisson-1-jeux-5-pieces-315', 'instrument', 'pinces-prehension', 'Pince Kerisson / 1 Jeux = 5 Pieces', 'Kerrison Forceps, Set of 5', '', ARRAY['aesculap','lawton','mcm','surgicon']::text[]),
  ('pince-kocher-15-cm-316', 'instrument', 'pinces-prehension', 'Pince Kocher 15 cm', 'Kocher Forceps, 15cm', '', ARRAY['aesculap','holtex','integra','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('pince-kocher-18-cm-317', 'instrument', 'pinces-prehension', 'Pince Kocher 18 cm', 'Kocher Forceps, 18cm', '', ARRAY['aesculap','holtex','integra','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('pince-kocher-a-g-15-cm-318', 'instrument', 'pinces-prehension', 'Pince Kocher A/G 15 cm', 'Kocher Forceps, Toothed/Non-Toothed, 15cm', '', ARRAY['aesculap','holtex','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('pince-kocher-a-g-16-cm-319', 'instrument', 'pinces-prehension', 'Pince Kocher A/G 16 cm', 'Kocher Forceps, Toothed/Non-Toothed, 16cm', '', ARRAY['aesculap','holtex','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('pince-leriche-courbe-s-g-16-cm-320', 'instrument', 'pinces-prehension', 'Pince Leriche Courbe S/G 16 cm', 'Leriche Forceps, Curved, without Teeth, 16cm', '', ARRAY['aesculap','holtex','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('pince-longuette-courbe-24-cm-321', 'instrument', 'pinces-prehension', 'Pince Longuette Courbe 24 cm', 'Sponge Forceps, Curved, 24cm', '', ARRAY['aesculap','holtex','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('pince-magique-322', 'instrument', 'pinces-prehension', 'Pince Magique', 'Magic Forceps', '', ARRAY['lawton','smith-nephew']::text[]),
  ('pince-museux-pour-coelio-diam-10-l33-cm-323', 'instrument', 'optiques-endoscopie', 'Pince Museux Pour Coelio Diam 10 L33 cm', 'Grasping Forceps for Laparoscopy, 10mm Diameter, L33cm', '', ARRAY['aesculap','lawton','mcm','reda','rz-medizin']::text[]),
  ('pince-passe-fil-45-vers-la-droite-324', 'instrument', 'pinces-prehension', 'Pince Passe Fil 45 Vers La Droite', 'Suture Passer, 45°, Right', '', ARRAY['lawton','precisa','reda','smith-nephew']::text[]),
  ('pince-passe-fil-45-vers-la-gauche-325', 'instrument', 'pinces-prehension', 'Pince Passe Fil 45 Vers La Gauche', 'Suture Passer, 45°, Left', '', ARRAY['lawton','precisa','reda','smith-nephew']::text[]),
  ('pince-passe-fil-courbe-vers-la-droite-326', 'instrument', 'pinces-prehension', 'Pince Passe Fil Courbe Vers La Droite', 'Suture Passer, Curved, Right', '', ARRAY['lawton','precisa','smith-nephew']::text[]),
  ('pince-passe-fil-courbe-vers-la-gauche-327', 'instrument', 'pinces-prehension', 'Pince Passe Fil Courbe Vers La Gauche', 'Suture Passer, Curved, Left', '', ARRAY['lawton','precisa','smith-nephew']::text[]),
  ('pince-pean-s-g-droit-14-cm-328', 'instrument', 'pinces-prehension', 'Pince Pean S/G Droit 14 cm', 'Pean Forceps, without Teeth, Straight, 14cm', '', ARRAY['aesculap','holtex','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('pince-plate-329', 'instrument', 'pinces-prehension', 'Pince Plate', 'Flat Forceps', '', ARRAY['aesculap','holtex','integra','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('pince-pour-biopcie-ref-27072mc-330', 'instrument', 'pinces-prehension', 'Pince Pour Biopcie Ref 27072MC', 'Biopsy Forceps, Ref 27072MC', '', ARRAY['lawton','reda']::text[]),
  ('pince-prehension-331', 'instrument', 'pinces-prehension', 'Pince Prehension', 'Grasping Forceps', '', ARRAY['lawton','mcm','precisa','reda','smith-nephew']::text[]),
  ('pince-resano-23cm-332', 'instrument', 'pinces-prehension', 'Pince Resano 23cm', 'Resano Forceps, 23cm', '', ARRAY['aesculap','integra','lawton','mcm','nopa','precisa']::text[]),
  ('pince-ronde-pour-boite-broche-333', 'instrument', 'pinces-prehension', 'Pince Ronde Pour Boite Broche', 'Round Forceps for K-Wire Case', '', ARRAY['aesculap','lawton','reda']::text[]),
  ('pince-rongeur-neuro-gm-334', 'instrument', 'pinces-prehension', 'Pince Rongeur Neuro Gm', 'Rongeur Forceps, Neuro, Large', '', ARRAY['aesculap','lawton','mcm','reda']::text[]),
  ('pinces-a-clip-d10mm-medium-large-335', 'instrument', 'pinces-prehension', 'Pinces A Clip D10mm Medium Large', 'Clip Appliers, 10mm, Medium/Large', '', ARRAY['ackerma','aesculap','hermann','lawton','mcm','olympus','precisa','reda','rz-medizin']::text[]),
  ('pinces-a-coeur-16cm-336', 'instrument', 'pinces-prehension', 'Pinces À Cœur 16cm', 'Heart-Shaped Forceps, 16cm', '', ARRAY['aesculap','holtex','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('pinces-d-alice-14cm-337', 'instrument', 'pinces-prehension', 'Pinces D''Alice 14cm', 'Allis Forceps, 14cm', '', ARRAY['aesculap','holtex','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('pinces-de-baquet-338', 'instrument', 'pinces-prehension', 'Pinces De Baquet', 'Basin Forceps', '', ARRAY['aesculap','holtex','lawton','mcm','nopa','precisa','reda']::text[]),
  ('pinces-de-maryland-d-05mm-339', 'instrument', 'pinces-prehension', 'Pinces De Maryland D 05mm', 'Maryland Forceps, 05mm Diameter', '', ARRAY['aesculap','hermann','lawton','mcm','olympus','reda','rz-medizin','tontarra','wolf']::text[]),
  ('pinces-fenetree-mors-26mm-d-05mm-340', 'instrument', 'pinces-prehension', 'Pinces Fenetree Mors 26mm D 05mm', 'Fenestrated Forceps, 26mm Jaw, 05mm Diameter', '', ARRAY['aesculap','hermann','lawton','mcm','olympus','reda','rz-medizin','tontarra','wolf']::text[]),
  ('pinces-museux-type-crocodile-diam-10mm-341', 'instrument', 'pinces-prehension', 'Pinces Museux Type Crocodile Diam 10mm', 'Grasping Forceps, Crocodile-Type, 10mm Diameter', '', ARRAY['aesculap','hermann','lawton','mcm','olympus','reda','rz-medizin','tontarra']::text[]),
  ('plan-incline-pour-le-traitement-des-seins-342', 'equipment', 'autre', 'Plan Incline Pour Le Traitement Des Seins', 'Inclined Positioning Board for Breast Treatment', '', ARRAY['ruidi']::text[]),
  ('plaque-pour-dermatome-345', 'instrument', 'autre', 'Plaque Pour Dermatome', 'Plate for Dermatome', '', ARRAY['mcm']::text[]),
  ('plateau-inox-346', 'instrument', 'autre', 'Plateau Inox', 'Stainless Steel Tray', '', ARRAY['mcm','nopa','surgicon']::text[]),
  ('poignet-americain-nez-americain-347', 'instrument', 'autre', 'Poignet Americain Nez Americain', 'American-Style Handle, American Nose', '', ARRAY['lawton','precisa','reda']::text[]),
  ('porte-aiguille-18-cm-348', 'instrument', 'aiguilles-canules', 'Porte-Aiguille 18 cm', 'Needle Holder, 18cm', '', ARRAY['aesculap','holtex','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('porte-aiguille-30cm-349', 'instrument', 'aiguilles-canules', 'Porte Aiguille 30cm', 'Needle Holder, 30cm', '', ARRAY['aesculap','holtex','integra','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('porte-aiguille-castrofijo-350', 'instrument', 'aiguilles-canules', 'Porte Aiguille Castrofijo', 'Castroviejo Needle Holder', '', ARRAY['aesculap','holtex','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('porte-aiguille-crile-wood-15-cm-351', 'instrument', 'aiguilles-canules', 'Porte-Aiguille Crile Wood 15 cm', 'Crile-Wood Needle Holder, 15cm', '', ARRAY['aesculap','holtex','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('porte-aiguille-mayo-hegar-l-14-352', 'instrument', 'aiguilles-canules', 'Porte Aiguille Mayo Hegar L 14', 'Mayo-Hegar Needle Holder, L14', '', ARRAY['aesculap','holtex','integra','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('porte-aiguille-mayo-hegar-l-16-353', 'instrument', 'aiguilles-canules', 'Porte Aiguille Mayo Hegar L 16', 'Mayo-Hegar Needle Holder, L16', '', ARRAY['aesculap','holtex','integra','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('porte-aiguille-mayo-hegar-l-18-354', 'instrument', 'aiguilles-canules', 'Porte Aiguille Mayo Hegar L 18', 'Mayo-Hegar Needle Holder, L18', '', ARRAY['aesculap','holtex','integra','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('porte-aiguille-mayo-hegar-l-20-355', 'instrument', 'aiguilles-canules', 'Porte Aiguille Mayo Hegar L 20', 'Mayo-Hegar Needle Holder, L20', '', ARRAY['aesculap','holtex','integra','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('porte-aiguille-mors-forts-et-courts-pour-aiguilles-2-0-d5mm-356', 'instrument', 'aiguilles-canules', 'Porte Aiguille Mors Forts Et Courts Pour Aiguilles 2/0 D5mm', 'Needle Holder, Strong Short Jaws, for 2/0 Needles, D5mm', '', ARRAY['aesculap','hermann','lawton','mcm','olympus','reda','rz-medizin','tontarra']::text[]),
  ('porte-aiguille-vasculaire-357', 'instrument', 'aiguilles-canules', 'Porte Aiguille Vasculaire', 'Vascular Needle Holder', '', ARRAY['aesculap','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('porte-batterie-358', 'instrument', 'autre', 'Porte Batterie', 'Battery Holder', '', ARRAY['lawton']::text[]),
  ('pousses-noeud-diam-05mm-359', 'instrument', 'autre', 'Pousses Nœud Diam 05mm', 'Knot Pusher, 05mm Diameter', '', ARRAY['aesculap','hermann','lawton','mcm','olympus','reda','rz-medizin','tontarra']::text[]),
  ('pousses-serringue-360', 'equipment', 'autre', 'Pousses Serringue', 'Syringe Pump', '', ARRAY['3m-bair-hugger','enmind','hawkmed','medcaptain','mindray','sinomdt']::text[]),
  ('presse-pour-plaques-arbre-fixe-361', 'instrument', 'autre', 'Presse Pour Plaques + Arbre Fixe', 'Plate Press + Fixed Shaft', '', ARRAY['reda']::text[]),
  ('radio-mobile-362', 'equipment', 'imagerie', 'Radio Mobile', 'Mobile X-Ray Unit', 'XR240', ARRAY['allengers','italray','perlove','siemens','smam','stephanix','traveller','villa']::text[]),
  ('radio-mobile-analogique-363', 'equipment', 'imagerie', 'Radio Mobile Analogique', 'Mobile X-Ray Unit, Analog', 'PLYMOBIL PLUS', ARRAY['gmm','italray','siemens','smam','stephanix','traveller']::text[]),
  ('rechauffeur-364', 'equipment', 'autre', 'Rechauffeur', 'Warmer', '', ARRAY['3m-bair-hugger','lifotronic']::text[]),
  ('rechauffeur-a-sang-365', 'equipment', 'autre', 'Réchauffeur À Sang', 'Blood Warmer', '', ARRAY['bair-hugger']::text[]),
  ('rechauffeur-de-gaz-pour-la-nouvelle-colonne-de-coelio-4k-366', 'equipment', 'bloc-operatoire', 'Rechauffeur De Gaz Pour La Nouvelle Colonne De Coelio 4K', 'Gas Warmer for the New 4K Laparoscopy Tower', '', ARRAY['conmed','olympus']::text[]),
  ('rechauffeurs-pour-malade-367', 'equipment', 'autre', 'Réchauffeurs Pour Malade', 'Patient Warmers', '', ARRAY['bair-hugger','lifotronic']::text[]),
  ('reducteurs-11mm-5-5mm-368', 'instrument', 'autre', 'Reducteurs 11mm/5.5mm', 'Reducers, 11mm/5.5mm', '', ARRAY['aesculap','hermann','lawton','mcm','olympus','reda','rz-medizin','tontarra']::text[]),
  ('refrigerateur-medicaments-369', 'equipment', 'autre', 'Refrigérateur Médicaments', 'Medication Refrigerator', '', ARRAY['libherr']::text[]),
  ('regine-de-cobb-6-8-12mm-370', 'instrument', 'autre', 'Regine De Cobb 6/8/12mm', 'Cobb Raspatory, 6/8/12mm', '', ARRAY['aesculap','lawton','mcm','nopa','precisa','reda']::text[]),
  ('resecteur-complet-ch24-371', 'instrument', 'optiques-endoscopie', 'Resecteur Complet Ch24', 'Complete Resectoscope, Ch24', '', ARRAY['lawton','reda','rz-medizin','tontarra']::text[]),
  ('resecteur-lame-372', 'instrument', 'optiques-endoscopie', 'Resecteur + Lame', 'Resectoscope + Blade', '', ARRAY['lawton','reda','tontarra']::text[]),
  ('respirateur-de-rea-module-metabolisme-crf-373', 'equipment', 'reanimation', 'Respirateur De Réa, Module Métabolisme + Crf', 'ICU Ventilator, with Metabolism Module + FRC', 'R860', ARRAY['aeonmed','drager','mindray','siare']::text[]),
  ('respirateur-de-transport-374', 'equipment', 'reanimation', 'Respirateur De Transport', 'Transport Ventilator', '', ARRAY['osiris']::text[]),
  ('respirateurs-de-rea-375', 'equipment', 'reanimation', 'Respirateurs De Rea', 'ICU Ventilators', 'MONNAL T75', ARRAY['aeonmed','air-liquide-medical-systems','axent','comen','drager','lowentein','magnamed','maquet','mindray','siar','sirusmed']::text[]),
  ('rongeur-cushing-str-180mm-2-10mm-376', 'instrument', 'autre', 'Rongeur Cushing Str 180mm,2*10mm', 'Cushing Rongeur, Straight, 180mm, 2x10mm', '', ARRAY['aesculap','integra']::text[]),
  ('rongeur-cushing-str-180mm-2x10mm-377', 'instrument', 'autre', 'Rongeur Cushing Str 180mm 2x10mm', 'Cushing Rongeur, Straight, 180mm, 2x10mm', '', ARRAY['lawton','mcm','nopa','reda']::text[]),
  ('rongeur-cushing-str180mm-1-5x10mm-378', 'instrument', 'autre', 'Rongeur Cushing Str180mm 1.5x10mm', 'Cushing Rongeur, Straight, 180mm, 1.5x10mm', '', ARRAY['lawton','mcm','reda']::text[]),
  ('rongeur-love-grunw-str-and-up-180mm-3-10mm-379', 'instrument', 'autre', 'Rongeur Love-Grunw,Str And Up 180mm,3*10mm', 'Love-Gruenwald Rongeur, Straight and Up, 180mm, 3x10mm', '', ARRAY['aesculap','integra']::text[]),
  ('rongeur-love-grunw-str-and-up-180mm-3x10mm-380', 'instrument', 'autre', 'Rongeur Love-Grunw Str And Up 180mm 3x10mm', 'Love-Gruenwald Rongeur, Straight and Up, 180mm, 3x10mm', '', ARRAY['lawton','mcm','nopa','reda']::text[]),
  ('rongeur-spurling-str-180mm-4-10mm-381', 'instrument', 'autre', 'Rongeur Spurling,Str 180mm,4*10mm', 'Spurling Rongeur, Straight, 180mm, 4x10mm', '', ARRAY['aesculap','integra']::text[]),
  ('rongeur-spurling-str-180mm-4x10mm-382', 'instrument', 'autre', 'Rongeur Spurling Str 180mm 4x10mm', 'Spurling Rongeur, Straight, 180mm, 4x10mm', '', ARRAY['lawton','mcm','nopa','reda']::text[]),
  ('rugine-de-cobb-09-5-mm-long-30-mm-383', 'instrument', 'autre', 'Rugine De Cobb 09.5 mm Long 30 mm', 'Cobb Raspatory, 09.5mm, 30mm Long', '', ARRAY['aesculap','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('rugine-de-cobb-13-mm-long-30-cm-384', 'instrument', 'autre', 'Rugine De Cobb 13 mm Long 30 cm', 'Cobb Raspatory, 13mm, 30cm Long', '', ARRAY['aesculap','lawton','mcm','nopa','reda','surgicon']::text[]),
  ('rugine-de-cobb-19-mm-long-30-cm-385', 'instrument', 'autre', 'Rugine De Cobb 19 mm Long 30 cm', 'Cobb Raspatory, 19mm, 30cm Long', '', ARRAY['aesculap','lawton','mcm','reda','surgicon']::text[]),
  ('rugine-droite-faraboeuf-15cm-12-5mm-386', 'instrument', 'autre', 'Rugine Droite (Faraboeuf) 15cm ; 12.5mm', 'Farabeuf Raspatory, Straight, 15cm, 12.5mm', '', ARRAY['aesculap','holtex','lawton','mcm','nopa','precisa','reda']::text[]),
  ('scialytique-mobile-avec-batterie-387', 'equipment', 'bloc-operatoire', 'Scialytique Mobile Avec Batterie', 'Mobile Surgical Light with Battery', '', ARRAY['danmedics','drager','elips','medifa','mindray']::text[]),
  ('scialytiques-plafonnieres-388', 'equipment', 'bloc-operatoire', 'Scialytiques Plafonnieres', 'Ceiling-Mounted Surgical Lights', '', ARRAY['acem','danmedics','drager','elips','medifa','mindray']::text[]),
  ('serre-noeud-389', 'instrument', 'porte-aiguilles-sutures', 'Serre Nœud', 'Knot Pusher', '', ARRAY['aesculap','lawton','mcm','reda','tontarra']::text[]),
  ('spatule-double-391', 'instrument', 'ecarteurs', 'Spatule Double', 'Double-Ended Spatula', '', ARRAY['aesculap','lawton','mcm','precisa','reda']::text[]),
  ('spatule-double-large-392', 'instrument', 'ecarteurs', 'Spatule Double Large', 'Double-Ended Spatula, Wide', '', ARRAY['aesculap','holtex','lawton','mcm','precisa','reda']::text[]),
  ('spatule-double-mousse-393', 'instrument', 'ecarteurs', 'Spatule Double Mousse', 'Double-Ended Spatula, Blunt', '', ARRAY['aesculap','lawton','mcm','precisa','reda']::text[]),
  ('spatule-freer-20cm-6-5mm-394', 'instrument', 'ecarteurs', 'Spatule Freer 20cm ; 6.5mm', 'Freer Spatula, 20cm, 6.5mm', '', ARRAY['aesculap','lawton','mcm','nopa','precisa','reda']::text[]),
  ('spatule-sachs-18cm-5mm-395', 'instrument', 'ecarteurs', 'Spatule (Sachs) 18cm ; 5mm', 'Sachs Spatula, 18cm, 5mm', '', ARRAY['aesculap','lawton','mcm','precisa','reda']::text[]),
  ('sternotome-396', 'instrument', 'autre', 'Sternotome', 'Sternotome', '', ARRAY['aesculap','lawton','mcm','reda','surgicon']::text[]),
  ('support-monbile-pour-bocale-d-aspiration-4-l-double-397', 'instrument', 'autre', 'Support Monbile Pour Bocale D''Aspiration 4 L Double', 'Mobile Stand for Suction Canisters, 4L, Double', '', ARRAY['a2-medical']::text[]),
  ('table-de-radiologie-numerisee-400', 'equipment', 'imagerie', 'Table De Radiologie Numérisée', 'Digital Radiology Table', 'PRECISION 180', ARRAY['angell','dms','famed','gmm','perlove','precision','stephanix','villa']::text[]),
  ('tabourets-401', 'equipment', 'mobilier-transport', 'Tabourets', 'Stools', '', ARRAY['amel']::text[]),
  ('tire-bouchon-402', 'instrument', 'autre', 'Tire Bouchon', 'Corkscrew', '', ARRAY['mcm']::text[]),
  ('trocart-de-cushing-pour-ponction-403', 'instrument', 'optiques-endoscopie', 'Trocart De Cushing (Pour Ponction)', 'Cushing Trocar (for Puncture)', '', ARRAY['aesculap','lawton','mcm','reda']::text[]),
  ('trocarts-d11mm-avec-mandrin-404', 'instrument', 'optiques-endoscopie', 'Trocarts D11mm Avec Mandrin', 'Trocars, 11mm, with Obturator', '', ARRAY['aesculap','hermann','lawton','mcm','olympus','reda','rz-medizin','tontarra','wolf']::text[]),
  ('trocarts-d5-5mm-avec-mandrin-405', 'instrument', 'optiques-endoscopie', 'Trocarts D5.5mm Avec Mandrin', 'Trocars, 5.5mm, with Obturator', '', ARRAY['aesculap','hermann','lawton','mcm','olympus','reda','rz-medizin','tontarra','wolf']::text[]),
  ('unite-endoscopie-406', 'equipment', 'imagerie', 'Unité Endoscopie', 'Endoscopy Unit', '', ARRAY['fujifilm','olympus','sonoscape']::text[]),
  ('ureteroscope-semi-rigide-contenaire-407', 'equipment', 'autre', 'Urétéroscope Semi-Rigide + Contenaire', 'Semi-Rigid Ureteroscope + Container', '', ARRAY['herman','olympus','wolf']::text[]),
  ('v1-408', 'equipment', 'autre', 'V1', 'V1', '', ARRAY['aeonmed','airon','weinmann']::text[]),
  ('v2-409', 'equipment', 'autre', 'V2', 'V2', '', ARRAY['axent','biomed','drager','falco-evo','magnamed','philips','resmed','weinmann']::text[]),
  ('v3-410', 'equipment', 'autre', 'V3', 'V3', '', ARRAY['mindray','weinmann']::text[]),
  ('valve-lumineuse-chirurgie-esthetique-411', 'instrument', 'autre', 'Valve Lumineuse Chirurgie Esthétique', 'Lighted Retractor Blade, Aesthetic Surgery', '', ARRAY['aesculap']::text[]),
  ('video-colonoscope-gastroscopie-412', 'equipment', 'imagerie', 'Vidéo-Colonoscope+Gastroscopie', 'Video Colonoscope + Gastroscope', '', ARRAY['aouha','olympus']::text[]),
  ('video-laryngoscope-413', 'equipment', 'autre', 'Vidéo Laryngoscope', 'Video Laryngoscope', '', ARRAY['medcaptain']::text[])
on conflict (id) do update set type=excluded.type, category=excluded.category, name_fr=excluded.name_fr, name_en=excluded.name_en, model=excluded.model, brand_ids=excluded.brand_ids;
